// Arena base-theme elimination narration.
// Templates use {killer}, {victim}, and optionally {third}.
// Keep mechanics separate from flavor so server themes can override these pools.

export const PLAYER_KILLS = [
  "{killer} launches {victim} over the barricade before they can even process the disrespect.",
  "{killer} catches {victim} celebrating early and sends them straight out of the Arena.",
  "{killer} uses {victim}'s own momentum against them. One redirect later, {victim} is gone.",
  "{killer} ducks the charge. {victim} discovers there was absolutely nothing behind them but consequences.",
  "{killer} hoists {victim} up, takes one dramatic second to reconsider, and very deliberately does not.",
  "{killer} sends {victim} sailing over the ropes with the confidence of someone taking out the trash.",
  "{killer} catches {victim} on the apron and removes the last thing keeping them employed: their grip.",
  "{killer} turns a harmless shove into a full eviction. {victim} has left the premises.",
  "{killer} sweeps {victim}'s legs at exactly the wrong place and exactly the right time.",
  "{killer} shoulder-checks {victim} so cleanly that the Arena briefly becomes an airport departure gate.",
  "{killer} blocks the escape route and boots {victim} into unemployment.",
  "{killer} waits for {victim} to turn around. Rookie mistake. Catastrophic outcome.",
  "{killer} grabs {victim} by the waistband and performs the least dignified elimination of the night.",
  "{killer} catches {victim} mid-taunt and converts confidence directly into floor time.",
  "{killer} plants both feet and sends {victim} backward over the edge like a folding chair with opinions.",
  "{killer} survives the scramble. {victim} does not. That's really the whole story.",
  "{killer} fakes left, goes right, and {victim} goes out.",
  "{killer} drags {victim} off the turnbuckle and straight into the eliminated column.",
  "{killer} interrupts {victim}'s comeback after approximately four seconds of hope.",
  "{killer} catches {victim}'s kick, smiles, and introduces them to gravity.",
  "{killer} reverses the reversal of the reversal. {victim} loses track somewhere around reversal two and gets dumped.",
  "{killer} sends {victim} through the ropes, then helpfully makes sure both feet touch the floor.",
  "{killer} peels {victim} off the ropes one finger at a time. Petty. Effective.",
  "{killer} wins a frantic edge battle by roughly one functioning brain cell.",
  "{killer} bounces {victim} off the corner and follows with a clothesline that ends their evening.",
  "{killer} catches {victim} trying to crawl back in and closes the door on that little dream.",
  "{killer} turns {victim}'s heroic last stand into a very short documentary.",
  "{killer} sees {victim} hanging on and chooses violence with admirable efficiency.",
  "{killer} uses the ropes like a slingshot. Unfortunately, {victim} is the ammunition.",
  "{killer} sends {victim} out sideways, which somehow makes the whole thing look even more insulting.",
  "{killer} catches {victim} distracted by the crowd. The crowd immediately pretends they had nothing to do with it.",
  "{killer} charges. {victim} braces. The brace accomplishes absolutely nothing.",
  "{killer} turns a handshake fake-out into an elimination. Trust issues unlocked.",
  "{killer} lets {victim} think they escaped, then taps them off the apron with one deeply disrespectful finger.",
  "{killer} muscles {victim} over the top after a struggle that becomes increasingly embarrassing for both of them.",
  "{killer} throws {victim} out and immediately looks for somebody else to inconvenience.",
  "{killer} catches {victim} airborne and changes their destination without consulting them.",
  "{killer} uses the corner post as an accomplice. {victim} files no complaint because they're already gone.",
  "{killer} yanks the rope down at the perfect moment. {victim} completes the rest of the elimination personally.",
  "{killer} shoves {victim} into a pileup, waits for the rebound, then finishes the job.",
  "{killer} removes {victim} from the Arena with the urgency of someone clearing a browser history.",
  "{killer} wins the clinch and sends {victim} to ringside with absolutely no return ticket.",
  "{killer} catches {victim} trying to hide behind {third}. It buys them almost two additional seconds.",
  "{killer} and {victim} trade blows until {killer} remembers the objective is actually to throw people out.",
  "{killer} turns {victim}'s dramatic charge into a dramatic exit.",
  "{killer} sees an opening the size of a postage stamp and somehow fits an entire {victim} through it.",
  "{killer} sends {victim} over the ropes, catches them trying to skin-the-cat back in, and says absolutely not.",
  "{killer} eliminates {victim} while {victim} is busy arguing with someone who wasn't even in the fight.",
  "{killer} uses a perfectly timed hip toss. {victim}'s landing zone is unfortunately outside the Arena.",
  "{killer} wins the world's angriest game of king-of-the-hill. {victim} is no longer on the hill."
];

export const SELF_KILLS = [
  "{victim} charges full speed, misses literally everybody, and launches themselves out. Incredible work.",
  "{victim} climbs the ropes for something spectacular. It is spectacular. Just not for the reason intended.",
  "{victim} celebrates an elimination that did not happen and steps backward out of the Arena.",
  "{victim} attempts a springboard move and learns that the springboard portion was apparently optional.",
  "{victim} tries to skin-the-cat back inside, loses their grip, and quietly becomes someone else's highlight reel.",
  "{victim} backs away from a fight without checking where the Arena ends. The Arena ends.",
  "{victim} goes for a flying attack. Their target moves. Physics does not.",
  "{victim} tries to intimidate everyone by standing on the top rope. Gravity remains unimpressed.",
  "{victim} gets tangled in the ropes while entering dramatically and somehow eliminates themselves before the drama finishes.",
  "{victim} attempts to vault back into the action and vaults directly past it.",
  "{victim} ducks an imaginary attack and rolls straight under the bottom rope, then keeps rolling until both feet hit the floor.",
  "{victim} tries to use the ropes for leverage. The ropes decline the partnership.",
  "{victim} climbs onto the apron to taunt the crowd and discovers the apron is a terrible place for interpretive dance.",
  "{victim} slips during a charge, grabs the top rope for help, and accidentally catapults themselves into irrelevance.",
  "{victim} attempts the coolest move anyone has ever seen. Nobody sees it because {victim} immediately disappears over the edge.",
  "{victim} gets so committed to dodging left that they dodge completely out of the match.",
  "{victim} tries to fake an elimination, forgets the floor is real, and accidentally makes it official.",
  "{victim} points at someone across the Arena, starts talking shit, and walks directly backward over the edge.",
  "{victim} attempts to rebound off the ropes. The rebound has other plans.",
  "{victim} launches into a heroic comeback and heroically lasts three more seconds.",
  "{victim} tries to jump from one corner to another. The geometry is immediately revealed to be aspirational.",
  "{victim} gets one boot caught in the ropes, panics, and somehow turns a minor inconvenience into a full elimination.",
  "{victim} avoids three different attacks and then trips over absolutely nothing. RNG has a sense of humor.",
  "{victim} attempts a dramatic rope-walk. This is not a circus. The distinction becomes clear quickly.",
  "{victim} leans over the ropes to yell at a spectator and simply... keeps going.",
  "{victim} goes for a backflip nobody requested. The Arena accepts their resignation.",
  "{victim} tries to play dead near the edge. The commitment to the bit becomes legally binding.",
  "{victim} launches themselves off the turnbuckle and realizes halfway through that there was no plan after launch.",
  "{victim} gets dizzy from spinning around an opponent and wanders directly out of the match.",
  "{victim} tries to hop onto the apron, catches one foot, and produces a noise nobody will ever let them forget.",
  "{victim} dodges a chair that was not actually coming toward them and eliminates themselves anyway.",
  "{victim} takes a running start for reasons known only to {victim}. Those reasons die on impact with the floor.",
  "{victim} attempts to climb back in from the outside, remembers too late that both feet already touched. Nice cardio though.",
  "{victim} tries to moonwalk away from danger and moonwalks directly into elimination.",
  "{victim} gets cocky, sits on the top rope, and immediately loses the argument with balance.",
  "{victim} performs an evasive roll so evasive that they evade the entire competition.",
  "{victim} tries to leapfrog an opponent who isn't there anymore. The floor is still there.",
  "{victim} decides the safest place is near the ropes. This conclusion survives for less than a second.",
  "{victim} attempts to dramatically remove a jacket mid-fight and gets trapped in it long enough to tumble out.",
  "{victim} tries to kick someone behind them, misses, spins around, and completes a beautiful accidental dismount.",
  "{victim} grabs the ropes to stop themselves, grabs the wrong rope, and somehow makes everything worse.",
  "{victim} attempts an unnecessary cartwheel. The word unnecessary does significant work here.",
  "{victim} climbs high for the crowd. The crowd receives {victim} shortly afterward.",
  "{victim} tries to sneak under everyone during a brawl and sneaks directly out of the Arena.",
  "{victim} gets startled by a completely unrelated impact and hops backward over the ropes on instinct.",
  "{victim} tries to stop on a dime. The dime wins.",
  "{victim} attempts a rope-assisted spin and invents a brand-new method of self-elimination.",
  "{victim} takes one confident step backward too many. There will be no second draft.",
  "{victim} tries to look cool leaning against the ropes. The ropes move. The coolness does not survive.",
  "{victim} sees chaos approaching, chooses flight, and accidentally takes that instruction literally."
];

export const PIN_DUELS = [
  "{winner} hooks the leg. {loser} kicks once, twice—too late. THREE. The Arena has made its decision.",
  "{winner} catches {loser} in a scramble and stacks them up. One. Two. Three. Done.",
  "{loser} nearly reverses the pin at two-and-nine-tenths. Nearly is doing devastating work in that sentence.",
  "{winner} survives a frantic exchange and drops straight into the cover. {loser} cannot beat the count.",
  "{winner} steals it with a sudden roll-up. {loser} is still trying to understand what happened when three hits.",
  "{loser} powers out at—nope. That's three. The hand hit first.",
  "{winner} plants {loser}, hooks both legs, and leaves absolutely no room for negotiation.",
  "{winner} counters the counter into a pin. One. Two. {loser} moves—after three.",
  "{loser} reaches desperately for leverage that does not exist. {winner} keeps the shoulders down for three.",
  "{winner} turns a wild collision into a cover before {loser} even knows they're flat on their back.",
  "{winner} traps {loser}'s shoulders in the ugliest pin imaginable. Ugly still counts to three.",
  "{loser} explodes upward a fraction of a second after the third count. The fraction is irrelevant.",
  "{winner} catches {loser} showboating and folds them into a flash pin. The crowd loses its mind.",
  "{winner} barely keeps the shoulders down through three. Barely is enough.",
  "{loser} gets one shoulder up. Unfortunately, it happens after the referee's hand has already hit three.",
  "{winner} drags {loser} away from the ropes and covers. No escape. Three.",
  "{winner} wins a brutal scramble for position and converts six seconds of chaos into a permanent elimination.",
  "{loser} tries to bridge out. {winner} collapses the bridge and gets the third count.",
  "{winner} rolls through {loser}'s attack and somehow emerges holding the winning pin.",
  "{loser} kicks out so close to three that half the Arena starts arguing. The official doesn't care.",
  "{winner} catches both legs and stacks {loser} like misplaced furniture. Three.",
  "{winner} turns {loser}'s last desperate attack into the exact opening needed for a pin.",
  "{loser} gets trapped beneath {winner} with nowhere to roll and nowhere to hide. One. Two. Three.",
  "{winner} hits the cover immediately. {loser} spends the entire count trying to remember which direction is up.",
  "{winner} uses pure leverage and questionable dignity to keep {loser} down for three.",
  "{loser} almost slips free. {winner} adjusts at two. The third count lands anyway.",
  "{winner} catches {loser}'s shoulders for exactly three seconds. That's all the Arena asks.",
  "{winner} survives the reversal, rolls back through, and steals the pin by inches.",
  "{loser} kicks, twists, and nearly escapes. {winner} hangs on like rent is due.",
  "{winner} collapses on top of {loser} after the exchange. Somehow that is enough. Three.",
  "{loser} gets cocky during the pin attempt and tries to reverse it. {winner} reverses the reversal and gets three.",
  "{winner} catches {loser} completely exhausted and makes the cover almost look merciful.",
  "{winner} pins {loser} with one arm while looking at the crowd. Disrespectful. Also successful.",
  "{loser} has one last burst left. It arrives approximately half a heartbeat too late.",
  "{winner} hooks the leg so tightly {loser} may need to file a missing-person report for it. Three.",
  "{winner} catches {loser} in a cradle. The entire thing is over before either of them can complain.",
  "{loser} tries to roll a shoulder up. {winner} shifts their weight. Three. Goodnight.",
  "{winner} drops into the cover after both fighters collapse. Only {winner} remembers to actually pin somebody.",
  "{winner} turns desperation into leverage and leverage into three counts.",
  "{loser} hears two and panics. Panic is not technically a kick-out.",
  "{winner} catches {loser} mid-reversal and simply refuses to let go until the third slap.",
  "{winner} wins by the smallest possible margin and celebrates like it was a forty-point blowout.",
  "{loser} reaches for the edge on instinct. There are no rope breaks in this pit. Three.",
  "{winner} uses {loser}'s own frantic momentum to roll them straight into the losing position.",
  "{winner} gets the shoulders down. {loser} gets the existential crisis. The count reaches three.",
  "{loser} escapes the first pin, the second pin, and absolutely not the third.",
  "{winner} finds one tiny opening in the scramble and jams an entire victory through it.",
  "{winner} catches {loser} flat-footed, flat-backed, and eventually flat-out eliminated.",
  "{loser} kicks out on instinct. The problem is their instinct fires after the match is already over.",
  "{winner} holds on through a violent last-second escape attempt. One. Two. THREE."
];

export const MULTI_PIN = [
  "Bodies everywhere. Somehow {winner} emerges on top of the pile when the third count lands. Everyone else is done.",
  "The pin becomes a human traffic accident. {winner} is the only person whose shoulders aren't trapped when three hits.",
  "Everyone tries to steal the cover at once. {winner} steals it better.",
  "The pile collapses, limbs go everywhere, and the count reaches three with {winner} inexplicably surviving.",
  "Nobody seems entirely sure who is pinning whom until the official points at {winner}. Apparently that's the answer.",
  "The entire pit turns into one frantic stack of bad decisions. {winner} is the last decision standing.",
  "Three competitors think they have the winning pin. Only {winner} is correct.",
  "The count starts while half the pit is still fighting over whose shoulders are actually down. At three, only {winner} is safe.",
  "A chain of reversals rolls across the floor like a car crash in slow motion. {winner} ends up on top when it matters.",
  "Everyone piles in for the finish. {winner} somehow avoids being pinned by approximately the width of a bad idea.",
  "The official counts one body, then another, then gives up on geometry and counts the legal pin. {winner} survives.",
  "The pit becomes a knot of arms and legs. Three seconds later, {winner} is the only one allowed to untangle themselves as an active player.",
  "Someone screams that their shoulder was up. Someone else screams they weren't even being pinned. {winner} screams because they won.",
  "Every person in the pit goes for a last-second reversal. {winner}'s reversal happens to be the last last-second reversal.",
  "The crowd cannot see the pin. The fighters cannot see the pin. The official apparently can. {winner} survives."
];

export const REVIVAL_DUELS = [
  "{winner} claws their way back from elimination and leaves {loser} in the dead pile.",
  "{loser} gets within one heartbeat of returning. {winner} takes that heartbeat personally.",
  "{winner} wins the Revival Pit and gets another terrible opportunity to make questionable decisions.",
  "{winner} refuses to stay eliminated. {loser}, unfortunately, remains extremely eliminated.",
  "The Pit offers one ticket back. {winner} takes it directly out of {loser}'s hands.",
  "{winner} survives the dead-player brawl. The Arena reluctantly puts their name back on the active roster.",
  "{loser} sees daylight. {winner} shuts the door and walks through it instead.",
  "{winner} wins the right to come back and potentially get eliminated again almost immediately.",
  "{winner} drags themselves out of the Pit. {loser} reaches after them and gets absolutely nothing.",
  "One resurrection available. Two idiots interested. {winner} gets it.",
  "{winner} steals the return at the final moment. {loser} is left arguing with death itself.",
  "{winner} gets another life. Nobody said anything about using it wisely.",
  "The Revival Pit spits {winner} back into the Arena and keeps {loser} as payment.",
  "{loser} almost completes the comeback. {winner} completes it first.",
  "{winner} wins the world's least comforting second chance.",
  "{winner} crawls back into contention while {loser} gets promoted to spectator again.",
  "{winner} punches their return ticket. {loser}'s ticket has been aggressively voided.",
  "{winner} survives the Pit by inches and returns with absolutely no immunity whatsoever. Good luck.",
  "{loser} was one RNG roll from resurrection. {winner} was the other RNG roll.",
  "Death opens the door for one person. {winner} shoulder-checks {loser} and goes through first."
];

export const BASE_DEATH_COUNTS = {
  player: PLAYER_KILLS.length,
  self: SELF_KILLS.length,
  pin: PIN_DUELS.length,
  multiPin: MULTI_PIN.length,
  revival: REVIVAL_DUELS.length
};
