const pick=(a,r=Math.random)=>a[Math.floor(r()*a.length)];
const joinNames=a=>a.length<2?(a[0]||"someone"):a.length===2?`${a[0]} and ${a[1]}`:`${a.slice(0,-1).join(", ")}, and ${a.at(-1)}`;

const VQS_OPEN=["The basement door slams shut and the lights die.","Every mirror in the hallway cracks at the exact same time.","The séance table flips itself before anyone touches it.","The nursery music starts playing from somewhere inside the walls.","The rotting greenhouse locks from the outside.","A hallway that absolutely was not there a second ago opens behind them.","The crawlspace exhales cold air and something starts pounding from the other side.","Every EXIT sign points toward the same locked room.","The chandelier drops low enough to turn the room into instant chaos.","The house kills the lights and apparently rings the bell for round one."];
const VQS_MID=["Nobody agrees on who swung first, but everybody commits immediately.","A temporary alliance lasts roughly three seconds before becoming a betrayal.","Someone screams that the floor moved. The floor, insultingly, moves again.","Half the group tries to escape while the other half decides this is somehow a fighting opportunity.","A possessed chair enters the situation and contributes far more than furniture should.","One contestant hides behind a wardrobe while everyone else turns the room into a disaster.","The mirrors keep showing attacks a second before they happen, which somehow makes everything worse.","A door opens, everybody rushes it, and the house immediately changes its mind.","The room temperature drops hard enough that nobody can tell whether they're shaking from fear or adrenaline.","Something whispers one contestant's name and the entire group makes the deeply reasonable decision to attack each other instead."];
const VQS_END=["When the lights return, {survivors} are still standing. The house has fewer guests now.","The room finally goes quiet. {survivors} make it out. Nobody asks where the others went.","The door unlocks for {survivors}. It does not unlock for everybody.","By the time the mirrors stop shaking, {survivors} are the only ones still in the fight.","The house settles like nothing happened. {survivors} remain. That feels personal.","The screaming stops first. Then the furniture. {survivors} are still here.","A single light flickers back on over {survivors}. The Arena has made its cuts.","The hallway returns to normal dimensions around {survivors}. Normal is doing a lot of work there.","The music box stops. {survivors} survive the room. Several others very much do not.","The doors reopen around {survivors}. Whatever just happened is apparently considered resolved."];

const FT_OPEN=["A poker table goes over and the entire casino floor takes that personally.","Somebody yells ALL IN with absolutely no cards involved and everything immediately goes to shit.","A tray of chips hits the floor and six degenerates suddenly forget every social contract they've ever signed.","The sportsbook screens flash a bad beat at exactly the wrong moment.","Security starts walking over. This somehow makes everybody fight faster.","The roulette ball leaves the wheel and apparently signals the beginning of open warfare.","A cocktail gets knocked over onto a betting slip worth way too much money.","The cashier cage alarm chirps once and the floor becomes a fucking battle royale.","Someone touches another contestant's chip stack. There will be no mediation.","The dealer backs away from the table with the instincts of a person who has seen this exact kind of degen bullshit before."];
const FT_MID=["A two-person alliance forms, wins one exchange, and immediately collapses over imaginary profit sharing.","Someone uses a casino chair as cover while two others argue about who technically started it.","One contestant ducks behind the craps table and lets everybody else burn stamina for free.","A stack of chips becomes a projectile, a distraction, and somehow evidence in three separate bad decisions.","The fight spills past roulette, through blackjack, and directly into a security guard's resignation letter.","One contestant screams DOUBLE OR NOTHING. Nobody knows what the first bet was.","A temporary team-up lasts until somebody realizes there is only one winner and zero loyalty points for friendship.","The sportsbook crowd starts calling odds on the fight while it is still happening.","Somebody attempts a heroic table dive and turns the entire situation into six-person traffic.","A dealer calmly pulls the cards out of danger while everyone else loses their fucking minds."];
const FT_END=["When security finally gets there, {survivors} are still standing. The casino declines to explain the rest.","The chips stop rolling. {survivors} remain in action. Several bets have been graded as catastrophic.","The floor clears around {survivors}. Somewhere, an insurance adjuster just felt a disturbance in the Force.","By the time the pit boss arrives, {survivors} are the only contestants still in the game.","The bell ends absolutely nothing, but {survivors} survive the mess anyway.","The smoke clears around {survivors}. The house would like everyone to know this promotion was not approved.","Security reviews the footage and finds {survivors} still standing. They immediately stop reviewing the footage.","The casino music never stopped playing. {survivors} remain, which makes the whole thing considerably more disrespectful.","The tables are wrecked, the chips are everywhere, and {survivors} somehow still have action.","The pit finally goes quiet around {survivors}. The degen economy will never recover."];

const DW_OPEN=["A DWallet drop notification hits at the exact wrong second and the whole chat loses focus.","The Telegram group starts moving at terminal velocity and the Arena follows suit.","A wall of purple reactions floods the feed and somebody decides that means fight.","The DWallet bot posts GOOD LUCK and immediately creates the opposite atmosphere.","A click-to-claim button appears beside the action and absolutely nobody behaves normally about it.","Every phone in the group vibrates at once and the Arena turns into instant chaos.","A giant stack of Telegram stickers covers half the live feed and all remaining restraint disappears.","The community counter spikes for no useful reason and everybody takes it personally.","A tip notification chimes three times in a row and somehow becomes the opening bell.","The DWallet status panel refreshes mid-round and several players choose violence over reading comprehension."];
const DW_MID=["A temporary alliance forms in the chat, survives one exchange, and dies the second somebody remembers only one person wins.","Half the group is fighting while the other half is still trying to figure out who tagged them.","Someone reaches for the claim button instead of defending themselves and creates a six-person traffic problem.","The spectator chat starts posting play-by-play faster than the actual fight can happen.","A flood of reaction emojis makes it impossible to tell who started what, so everybody continues anyway.","One contestant tries to use a notification as a distraction and accidentally distracts their own teammate instead.","The bot keeps posting perfectly normal status updates while the players make the situation increasingly abnormal.","Two contestants agree to cooperate for approximately one message before immediately betraying each other.","Someone yells that a drop is live. It is not. The damage to everyone else's attention is already done.","The live player list keeps refreshing while the entire group turns the center of the Arena into a pileup."];
const DW_END=["When the feed catches up, {survivors} are still active. The group chat has several thousand new opinions.","The reactions finally slow down around {survivors}. Everyone else has been moved to spectator status.","The DWallet panel refreshes and keeps {survivors} on the active list. Several names disappear below them.","The bot posts the result without judgment: {survivors} survive the mess.","The chat scrolls past the wreckage and finds {survivors} still standing.","The player list settles with {survivors} still active. Nobody agrees on how that happened.","The purple status card updates around {survivors}. The community immediately demands a replay.","The notification storm ends. {survivors} remain in the Arena and everyone else gets the spectator view.","The DWallet feed returns to normal around {survivors}. Normal lasts almost three seconds.","The last sticker clears the screen and reveals {survivors} still standing. The Arena has made its cuts."];

function poolsForTheme(themeId){
  if(themeId==="full_tilt")return[FT_OPEN,FT_MID,FT_END];
  if(themeId==="dwallet")return[DW_OPEN,DW_MID,DW_END];
  return[VQS_OPEN,VQS_MID,VQS_END];
}

export function buildMassBrawl(themeId,names,survivorNames,rng=Math.random){
  const[opens,mids,ends]=poolsForTheme(themeId);
  const open=pick(opens,rng),mid=pick(mids,rng),end=pick(ends,rng).replace("{survivors}",joinNames(survivorNames));
  const intro=names.length>=6?`${joinNames(names)} all get dragged into it.`:`${joinNames(names)} get caught in the same mess.`;
  return`${open} ${intro} ${mid} ${end}`;
}

export const MASS_BRAWL_COMBINATIONS_PER_THEME=1000;
