// Vibe Queen Slots — horror Arena flavor.
// Spooky/fun rather than graphic: paranormal, slashers, cursed objects,
// haunted locations, creatures, urban legends, and cosmic weirdness.

export const VQS_HORROR = {
  id: "vibe_queen_slots",
  displayName: "Vibe Queen Slots: After Dark",
  tone: "playful_horror",
  contentRating: "spooky_non_graphic",
  labels: {
    arena: "THE HAUNTED ARENA",
    revival: "THE VEIL OPENS",
    crowdVote: "THE AUDIENCE CHOOSES",
    crowdPin: "THE FINAL SCARE"
  },

  playerKills: [
    "The lights die. When they return, {killer} is standing alone and {victim} is simply no longer in the Arena.",
    "{killer} points behind {victim}. {victim} actually looks. That was all the opening {killer} needed.",
    "A masked figure appears at ringside. {victim} freezes. {killer} very much does not.",
    "{killer} chases {victim} into the fog. Only {killer} comes back out.",
    "The old television in the corner flickers to life. {victim} stares one second too long. {killer} handles the rest.",
    "{victim} hears footsteps behind them. It's only {killer}. Somehow that's worse.",
    "A music box starts playing by itself. {victim} turns toward it and {killer} sends them straight out of the Arena.",
    "{killer} backs {victim} toward a door that absolutely was not there a moment ago. The door opens. Goodbye, {victim}.",
    "The Arena fills with cold mist. {killer} emerges from it at exactly the wrong moment for {victim}.",
    "{victim} spots a face in the mirror. {killer} spots an opportunity.",
    "A phone begins ringing somewhere in the dark. {victim} answers. {killer} apparently called collect.",
    "{killer} sends {victim} stumbling into the shadows. Something in there seems delighted to help finish the elimination.",
    "{victim} insists the mannequin moved. {killer} uses the distraction to prove something else can move too: {victim}, directly out.",
    "The lights flicker three times. On the third, {killer} is suddenly behind {victim}. Horror movie rules remain undefeated.",
    "{killer} traps {victim} between the ropes and a suspiciously patient scarecrow. {victim} chooses the ropes. Wrong choice.",
    "A child's laugh echoes through the Arena. {victim} stops dead. {killer} does not ask questions.",
    "{killer} leads {victim} straight toward the EXIT sign. Unfortunately, it means exit from the match.",
    "The floorboards creak beneath {victim}. {killer} gives them one little push and lets the haunted architecture take the credit.",
    "{victim} sees a shadow move where no person is standing. {killer} sees {victim} stop paying attention.",
    "{killer} disappears behind a curtain and somehow reappears on the other side of {victim}. Nobody requests an explanation.",
    "A porcelain doll slowly turns its head toward {victim}. {killer} capitalizes on the resulting absolutely reasonable panic.",
    "{killer} corners {victim} beside an antique wardrobe. Something knocks from inside. {victim} flinches directly into elimination.",
    "The emergency lights turn red. {killer} turns {victim}'s evening considerably darker.",
    "{victim} runs from {killer}, opens the wrong door, and finds the Arena edge waiting on the other side.",
    "A pale hand appears from beneath the ring and grabs {victim}'s ankle. {killer} shrugs and takes the assist.",
    "{killer} sends {victim} toward a row of empty theater seats. One seat folds down by itself. Nobody likes that.",
    "The grandfather clock strikes thirteen. {victim} looks confused. {killer} looks productive.",
    "{victim} hears their own voice whisper their name from behind them. {killer} is waiting when they turn around.",
    "{killer} and {victim} disappear into a patch of unnatural darkness. {killer} returns dusting off their hands.",
    "A figure in the balcony slowly points at {victim}. {killer} accepts the recommendation.",
    "The EXIT sign changes to RUN. {victim} obeys. {killer} redirects the route straight out of the Arena.",
    "{killer} catches {victim} hiding behind a sheet-covered statue. The statue turns its head. Both fighters decide to move; only {killer} moves correctly.",
    "{victim} follows a trail of flickering candles toward safety. {killer} is waiting at candle number six.",
    "A shadow crosses the ceiling. {victim} looks up. Classic mistake. {killer} sends them out.",
    "{killer} traps {victim} against a boarded-up doorway. The boards knock back. {victim} chooses immediate evacuation.",
    "The Arena speakers whisper, 'behind you.' {victim} turns around and discovers the speakers were technically correct.",
    "{killer} uses a rolling fog bank like tactical cover and materializes directly in {victim}'s personal nightmare.",
    "{victim} notices every clock in the Arena has stopped. {killer} makes sure their run stops too.",
    "A jack-o'-lantern lights itself at ringside. {victim} stares. {killer} supplies the jump scare.",
    "{killer} sends {victim} stumbling through a curtain marked DO NOT ENTER. The Arena considers that an elimination.",
    "A creepy little tricycle rolls across the floor by itself. {victim} sidesteps it and walks directly into {killer}.",
    "{victim} sees something crawling across the far wall. No one else does. {killer} is happy to exploit the disagreement.",
    "The chandelier swings without wind. {victim} watches it. {killer} watches {victim}.",
    "{killer} knocks on an empty coffin. Something knocks back. {victim} decides to leave and accidentally does so permanently.",
    "A hooded silhouette appears in the fog behind {victim}. {victim} bolts forward directly into {killer}'s elimination.",
    "{killer} sends {victim} toward the haunted-house elevator. The doors close. The floor indicator starts counting downward past zero.",
    "{victim} notices a second {killer} standing in the mirror. Unfortunately the first {killer} is still right behind them.",
    "The Arena goes silent—too silent. {killer} breaks the silence by eliminating {victim}.",
    "{killer} whistles from one side of the Arena while somehow standing on the other. {victim} never solves the mystery.",
    "A dusty portrait's eyes follow {victim}. {killer}'s eyes do too, but with significantly worse intentions for their match status."
  ],

  selfKills: [
    "{victim} hears someone whisper 'come here' from the fog and, astonishingly, goes there.",
    "A door creaks open by itself. {victim} walks through it. The door closes. That's apparently an elimination.",
    "{victim} follows mysterious footprints that lead directly out of the Arena. The footprints stop. {victim} does not.",
    "{victim} sees their reflection wave first and backs away so quickly they eliminate themselves.",
    "A rocking chair begins moving on its own. {victim} decides anywhere else is better and chooses outside the Arena.",
    "{victim} hears a chainsaw start somewhere nearby and exits the Arena with record-setting enthusiasm. False alarm. Still eliminated.",
    "{victim} notices a clown standing motionless in the corner. The clown tilts its head. {victim} is immediately done with this entire event.",
    "A balloon floats past with {victim}'s name written on it. {victim} follows it straight over the boundary.",
    "{victim} tries to hide inside an antique wardrobe. The wardrobe is suddenly somewhere outside the Arena. Nobody understands the logistics.",
    "{victim} hears three knocks beneath the floor and jumps directly out of the match.",
    "The lights turn off. {victim} screams, runs blindly, and discovers the edge before discovering the light switch.",
    "{victim} sees a doll blink. That's it. That's the whole reason. They leave.",
    "A television displays LIVE FOOTAGE of {victim} being eliminated five seconds from now. {victim} panics and fulfills the prophecy personally.",
    "{victim} opens a suspicious book titled DO NOT OPEN. A gust of wind immediately removes them from competition.",
    "{victim} hears breathing behind them, spins around, and backpedals straight out of the Arena. There was nobody there.",
    "A black cat crosses {victim}'s path. {victim} dramatically changes direction and accidentally changes their status to eliminated.",
    "{victim} tries to escape a swarm of completely ordinary moths and somehow turns it into a full evacuation.",
    "The mirror writes RUN in condensation. {victim} respects supernatural signage a little too enthusiastically.",
    "{victim} spots a pale face in the window. The Arena does not have windows. {victim} decides this is somebody else's problem.",
    "A creepy ringtone starts playing from {victim}'s pocket. Their phone is not in their pocket. {victim} exits immediately.",
    "{victim} hears a little kid ask 'want to play?' from an empty corner and chooses the fastest possible route away.",
    "The fog forms what looks suspiciously like a person. {victim} runs. The fog wins by technicality.",
    "{victim} reads DON'T LOOK BEHIND YOU scratched into the wall, looks behind them, screams, and falls out of the Arena.",
    "A handprint appears on {victim}'s shoulder with nobody nearby. {victim} retires from the match on the spot.",
    "{victim} hears their name coming from an unplugged radio and decides the afterlife can have the whole Arena.",
    "Every mannequin turns toward {victim} at once. {victim} achieves a personal best sprint directly out of competition.",
    "{victim} sees a figure at the end of a hallway that keeps getting closer without moving. {victim} solves this by leaving the building.",
    "A jack-in-the-box begins winding itself. {victim} refuses to wait for the payoff and eliminates themselves preemptively.",
    "{victim} steps into a circle of candles. Every flame goes out simultaneously. So does {victim}'s courage.",
    "The Arena speakers play {victim}'s own laugh back at them. {victim} would like to unsubscribe and does so violently.",
    "{victim} notices one extra person in the crowd who disappears whenever they blink. After blink four, {victim} is gone instead.",
    "A closet door slowly opens. {victim} says 'absolutely not' and leaves the Arena under their own power.",
    "{victim} hears footsteps matching theirs exactly. They stop. The footsteps don't. Goodbye.",
    "A shadow waves from beneath the ring. {victim} waves back. The shadow reaches up. {victim} immediately rethinks several life choices.",
    "The room suddenly smells like an old basement. {victim} decides that's enough paranormal activity for one evening.",
    "{victim} sees a message on the wall: YOU'RE NEXT. Technically the wall is correct.",
    "A music box begins playing backwards. {victim} goes forward—straight out of the Arena.",
    "{victim} finds a key labeled BASEMENT and drops it. Something beneath the floor picks it up. {victim} leaves.",
    "A portrait whispers {victim}'s username. {victim} logs out of the Arena in the most literal way possible.",
    "{victim} hears scratching inside the walls and decides elimination is preferable to investigating.",
    "A figure appears behind {victim} every time the lights flicker. On flicker six, {victim} simply gives up and exits.",
    "{victim} sees an empty wheelchair roll toward them. It isn't moving fast. {victim} is.",
    "The words TURN AROUND appear on the mirror. {victim} refuses, backs away, and falls directly out instead.",
    "A bell rings from somewhere underground. {victim} does not know what it means and has no interest in learning.",
    "{victim} discovers the creepy doll has moved from across the Arena to directly beside them. Match over. Voluntarily.",
    "An unseen voice whispers 'boo.' That's genuinely all it takes. {victim} is gone.",
    "{victim} sees a long-haired figure crawl out from behind the old television and achieves escape velocity.",
    "The lights reveal dozens of handprints around {victim}. The next frame reveals no {victim}.",
    "{victim} hears a slow knock from inside a locked trunk and decides second place sounds fantastic.",
    "A scarecrow that was outside is suddenly inside. {victim} becomes suddenly outside."
  ],

  pinDuels: [
    "The lights flicker through the count. ONE. Darkness. TWO. Darkness. THREE. When they return, only {winner} is still in the match.",
    "A music box begins playing as {winner} hooks {loser}. The final note lands exactly with THREE.",
    "{loser} reaches for the ropes. A pale hand is already resting there. They reconsider. Too late. THREE.",
    "The Arena goes ice-cold as {winner} traps {loser}'s shoulders. One. Two. Three.",
    "A shadow stretches across the pit while {winner} makes the cover. {loser} kicks out one heartbeat too late.",
    "The old clock strikes once for ONE, twice for TWO, and on the third strike {loser}'s night is over.",
    "{winner} catches {loser} in a sudden pin as every light in the Arena turns red. THREE.",
    "The crowd counts with the referee. Something else whispers the numbers from inside the walls. {winner} survives.",
    "{loser} almost escapes, but the fog curls around the edge of the pit like it has opinions. THREE.",
    "{winner} rolls {loser} into the cover. The television nearby displays THREE before the official even gets there. Unsettling. Accurate.",
    "A masked silhouette watches from the entrance while {winner} keeps {loser} down for the full count.",
    "{loser} hears their name whispered at TWO and looks toward the sound. That tiny distraction costs them THREE.",
    "{winner} pins {loser}. The lights blink once per count. On the third blink, the match is decided.",
    "A door slams somewhere in the Arena at the exact moment THREE lands. {loser} is officially locked out.",
    "{winner} holds the cover while the chandelier above them begins swinging. Nobody waits around after THREE.",
    "{loser} tries to bridge out. Their reflection in the nearby mirror doesn't move with them. Understandably distracting. THREE.",
    "{winner} catches {loser} in a flash pin. The creepy doll at ringside slowly claps. Nobody likes that, but the count stands.",
    "ONE. TWO. The lights die. THREE echoes through total darkness. When the emergency lights return, {winner}'s hand is raised.",
    "{loser} kicks out—after the third knock sounds from beneath the floor. The Pit has already chosen {winner}.",
    "{winner} traps {loser} beneath them as a distant phone rings three times. On ring three, it's over.",
    "The fog briefly hides both fighters. The official's hand still finds the floor three times. {winner} emerges alone.",
    "{loser} nearly reverses the pin until something in the empty balcony laughs. They freeze. THREE.",
    "{winner} gets the shoulders down while every candle around the Pit extinguishes one by one. The third count lands with the last flame.",
    "The Arena speakers whisper ONE... TWO... before the official does. Nobody asks who whispers THREE.",
    "{winner} survives the scramble and hooks the leg. Behind them, a door slowly opens. THREE. They wisely do not investigate.",
    "{loser} reaches toward the crowd. Every spectator points back toward {winner}. THREE.",
    "{winner} catches the winning pin as a shadow passes over both fighters despite there being nothing overhead.",
    "The referee counts three. A second, quieter voice counts four. {winner} leaves before finding out why.",
    "{loser} kicks at TWO. The old television shows them still pinned. Reality sides with the television. THREE.",
    "{winner} gets the cover while a figure stands motionless at the edge of the fog. At THREE, the figure is gone. So is {loser}."
  ],

  multiPins: [
    "The lights strobe through a pile of fighters. Each flash shows someone in a different position. On the final flash, only {winner} is safe.",
    "The fog swallows the entire Pit. The count reaches three somewhere inside it. {winner} is the only competitor who walks back out.",
    "Every fighter scrambles as the old clock begins counting. When it reaches three, {winner} is somehow the only one not pinned.",
    "A chorus of whispers counts along with the official. ONE. TWO. THREE. The Pit keeps everyone except {winner}.",
    "The lights go completely black during the pileup. Three slaps later they return, and {winner} is standing among several extremely unhappy new spectators.",
    "The mirror beside the Pit shows only {winner} before the count even begins. Three seconds later, reality catches up.",
    "Everyone fights for position while doors around the Arena slam one after another. The final door closes on everyone except {winner}.",
    "The pile shifts beneath a cloud of cold mist. The official reaches three and points to {winner}. Nobody argues with the mist.",
    "Every candle around the Pit goes dark except the one behind {winner}. Subtle, supernatural, and apparently legally binding.",
    "A masked figure watches the chaotic pin from the entrance. When the count hits three, it nods once at {winner} and disappears."
  ],

  revivalDuels: [
    "The Veil opens for exactly one soul. {winner} gets through before {loser} can reach the door.",
    "Two eliminated fighters hear the Arena calling. Only {winner} answers loudly enough.",
    "A doorway appears in the fog. {winner} crosses the threshold. It vanishes directly in front of {loser}.",
    "The old television flickers from ELIMINATED to ACTIVE beside {winner}'s name. {loser}'s screen stays dark.",
    "The candles relight around {winner}. The ones surrounding {loser} remain cold.",
    "Something beneath the Arena offers one second chance. {winner} takes it. {loser} gets a very uncomfortable silence.",
    "The music box plays forward for {winner} and backward for {loser}. Apparently that's the ruling.",
    "A bell rings once. {winner} wakes back into the match. {loser} remains on the wrong side of the Veil.",
    "{winner} follows a light through the fog and returns to the Arena. {loser} follows the same light and somehow ends up exactly where they started.",
    "The shadowy doorway chooses {winner}. Nobody remembers agreeing that the doorway was allowed to choose.",
    "{winner}'s name scratches itself back onto the active roster. {loser}'s name quietly fades.",
    "A voice from the darkness says one name: {winner}. That's apparently all the paperwork resurrection requires.",
    "{winner} crawls through the opening in the Veil just before it snaps shut on {loser}'s second chance.",
    "The Arena lights flicker back on around {winner}. {loser} remains somewhere beyond the blackout.",
    "One ghostly hand reaches through the Veil. {winner} grabs it first. Questionable decision, excellent result.",
    "The haunted clock winds backward for {winner} and gives them another life. It refuses to do the same for {loser}.",
    "{winner} hears the crowd through the fog and follows the sound home. {loser} hears only static.",
    "The EXIT sign over the Revival Pit changes to RETURN for exactly three seconds. {winner} makes it.",
    "{winner}'s reflection steps out of the mirror first. A moment later, the real {winner} follows. {loser} decides not to question any of this.",
    "The Veil tears open like a curtain. {winner} steps through. It stitches itself closed before {loser} can follow."
  ]
};
