export function activityPreviewHtml() {
  return `<!doctype html>
<html>
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width,initial-scale=1,viewport-fit=cover,user-scalable=no">
<title>DWallet Arena FX Lab</title>
<style>
:root{color-scheme:dark;--bg:#08070d;--panel:#14101d;--panel2:#1e172b;--purple:#9864ff;--purple2:#d0b9ff;--text:#f7f4ff;--muted:#aaa1b7;--danger:#ff4f78;--good:#59e6a7;--line:#342842;--amber:#ffbf5e}
*{box-sizing:border-box}html,body{margin:0;min-height:100%;background:radial-gradient(circle at 50% -15%,#24113c 0,#0d0915 42%,#08070d 72%);color:var(--text);font-family:Inter,ui-sans-serif,system-ui,-apple-system,BlinkMacSystemFont,"Segoe UI",sans-serif;overflow-x:hidden}body{padding:16px}.app{max-width:980px;margin:0 auto}.top{display:flex;align-items:flex-end;justify-content:space-between;gap:14px;margin-bottom:14px}.eyebrow{font-size:11px;letter-spacing:.22em;color:var(--purple2);font-weight:950}.title{font-size:clamp(28px,6vw,52px);font-weight:1000;line-height:.94;margin:7px 0 0}.sub{color:var(--muted);font-size:13px;max-width:560px}.badge{border:1px solid #583d7e;background:#1f1430;padding:7px 10px;border-radius:99px;font-size:10px;font-weight:900;letter-spacing:.1em;color:var(--purple2);white-space:nowrap}.grid{display:grid;grid-template-columns:minmax(0,1fr) 280px;gap:12px}.stage{position:relative;min-height:560px;background:linear-gradient(180deg,#171021,#0f0b16);border:1px solid var(--line);border-radius:24px;overflow:hidden;box-shadow:0 28px 80px rgba(0,0,0,.4)}.stage:before{content:"";position:absolute;inset:0;background:linear-gradient(rgba(255,255,255,.018) 1px,transparent 1px),linear-gradient(90deg,rgba(255,255,255,.014) 1px,transparent 1px);background-size:28px 28px;pointer-events:none}.stageHeader{position:relative;z-index:4;display:flex;justify-content:space-between;gap:12px;align-items:center;padding:16px;border-bottom:1px solid var(--line);background:rgba(9,7,14,.76);backdrop-filter:blur(12px)}.location{font-size:11px;letter-spacing:.16em;font-weight:950;color:var(--purple2)}.status{font:800 11px ui-monospace,SFMono-Regular,Menlo,monospace;color:#8d8499}.arena{position:relative;z-index:2;padding:22px;min-height:490px;display:flex;flex-direction:column;justify-content:center}.normalCard{max-width:620px;margin:auto;width:100%;background:linear-gradient(180deg,#21162f,#15101e);border:1px solid #3e2b54;border-radius:22px;padding:22px;box-shadow:0 22px 60px rgba(0,0,0,.34)}.round{font-size:11px;font-weight:950;letter-spacing:.14em;color:var(--purple2)}.headline{font-size:clamp(25px,5vw,44px);font-weight:1000;line-height:.98;margin:8px 0 12px}.copy{color:#d9d3e2;line-height:1.48}.roster{display:grid;grid-template-columns:repeat(3,1fr);gap:7px;margin-top:16px}.fighter{padding:10px;border:1px solid #352742;border-radius:12px;background:#120e19;font-size:12px;font-weight:850;display:flex;justify-content:space-between;gap:8px}.fighter.out{text-decoration:line-through;color:#796f84;filter:saturate(.4)}.fighter.hot{border-color:#7f56c5;box-shadow:0 0 0 1px rgba(152,100,255,.22),0 0 22px rgba(152,100,255,.16)}
.controls{background:linear-gradient(180deg,#151020,#0f0b16);border:1px solid var(--line);border-radius:24px;padding:14px;align-self:start;position:sticky;top:12px}.controls h3{margin:2px 0 6px;font-size:14px}.controls p{font-size:11px;color:var(--muted);line-height:1.35;margin:0 0 12px}.buttons{display:grid;gap:7px}.buttons button{appearance:none;border:1px solid #3b2b50;background:#20162d;color:var(--text);border-radius:12px;padding:11px 10px;font-weight:900;text-align:left;cursor:pointer}.buttons button:hover{border-color:#7654a5;background:#2b1d3c}.buttons button.primary{background:linear-gradient(135deg,#7d49ef,#a35cff);border-color:#ab7cff}.small{font-size:9px;color:#aaa0b7;font-weight:700;display:block;margin-top:3px}.haptic{margin-top:10px;border:1px dashed #463657;border-radius:11px;padding:9px;font:800 10px ui-monospace,SFMono-Regular,Menlo,monospace;color:#9e92aa}.haptic b{color:var(--purple2)}
.overlay{position:absolute;inset:0;z-index:20;display:flex;align-items:center;justify-content:center;padding:20px;background:rgba(4,3,7,.83);backdrop-filter:blur(8px);opacity:0;pointer-events:none;transition:opacity .2s}.overlay.show{opacity:1;pointer-events:auto}.fxPanel{width:min(720px,100%);text-align:center}.fxKicker{font:950 11px ui-monospace,SFMono-Regular,Menlo,monospace;letter-spacing:.2em;color:var(--purple2)}.fxTitle{font-size:clamp(36px,9vw,78px);font-weight:1000;line-height:.86;margin:12px 0;text-transform:uppercase}.fxSub{color:#c4bdce;font-size:14px}.chips{display:flex;flex-wrap:wrap;gap:8px;justify-content:center;margin:18px 0}.chip{border:1px solid #594079;background:#1d1429;border-radius:99px;padding:8px 12px;font-weight:900}.chip.dead{color:#8e8299;text-decoration:line-through;border-color:#402c42;background:#191016}.chip.live{border-color:#3d9c76;color:#9ff5cf;background:#10221c}.warning{color:#ff8aa5}.good{color:var(--good)}
.lockdown .stage{animation:shake .16s 4}.lockdown .stageHeader{background:#2a0c16}.lockdown .location{color:#ff839e}.lockdown .stage:after{content:"HQ LOCKDOWN";position:absolute;inset:auto 0 0;z-index:7;background:#9d173a;color:white;padding:6px;text-align:center;font:1000 10px ui-monospace,SFMono-Regular,Menlo,monospace;letter-spacing:.25em}.scanlines{position:absolute;inset:0;z-index:15;pointer-events:none;opacity:0;background:repeating-linear-gradient(0deg,rgba(255,255,255,.04),rgba(255,255,255,.04) 1px,transparent 1px,transparent 4px)}.glitching .scanlines{opacity:1;animation:scan .12s infinite}.glitching .stage{animation:glitch .13s 8}.glitching .location{animation:flicker .18s infinite}.finalfive .stage{box-shadow:inset 0 0 0 2px #6a467e,0 25px 80px rgba(0,0,0,.45)}.finalfive .stageHeader{background:#120d18}.finalfive .stage:after{content:"SPECIAL PROTOCOLS DISABLED // FINAL FIVE";position:absolute;z-index:8;top:0;left:0;right:0;height:3px;background:linear-gradient(90deg,transparent,#ad6cff,transparent);box-shadow:0 0 30px #9e5bff}
.voteWrap{display:grid;grid-template-columns:120px 1fr;gap:20px;align-items:center;margin:18px auto;max-width:650px}.ring{width:112px;height:112px;border-radius:50%;display:grid;place-items:center;background:conic-gradient(var(--purple) calc(var(--pct)*1%),#2b2036 0);position:relative}.ring:before{content:"";position:absolute;inset:9px;border-radius:50%;background:#0e0a14}.ring strong{position:relative;z-index:2;font-size:31px}.bars{display:grid;gap:9px;text-align:left}.barRow{display:grid;grid-template-columns:90px 1fr 28px;gap:8px;align-items:center;font-size:11px;font-weight:900}.bar{height:11px;background:#292032;border-radius:99px;overflow:hidden}.bar i{display:block;height:100%;background:linear-gradient(90deg,#7345d3,#c18cff);width:0;transition:width .4s}.vs{display:grid;grid-template-columns:1fr auto 1fr;gap:12px;align-items:center;margin:22px 0}.vsName{font-size:clamp(24px,6vw,48px);font-weight:1000}.vsBadge{font:1000 18px ui-monospace,SFMono-Regular,Menlo,monospace;color:#caaaFF}.restore{filter:grayscale(.75);animation:restore 1.2s ease both}.redButton{width:128px;height:128px;border-radius:50%;border:10px solid #371019;background:radial-gradient(circle at 35% 28%,#ff7b8f 0,#df234a 35%,#84142f 68%,#4a0d1c 100%);box-shadow:0 12px 0 #330912,0 0 0 7px #16080d,0 0 60px rgba(255,42,88,.35);margin:22px auto;animation:redpulse 1s infinite}.pressed{animation:press .45s ease forwards}.monitorGrid{display:grid;grid-template-columns:repeat(3,1fr);gap:7px;margin:18px auto;max-width:620px}.monitor{height:85px;border:1px solid #423450;background:linear-gradient(180deg,#120f18,#08070b);border-radius:7px;display:grid;place-items:center;font:800 9px ui-monospace,SFMono-Regular,Menlo,monospace;color:#877a92;position:relative;overflow:hidden}.monitor.hot{color:#dfcbff;border-color:#6f4fa0;box-shadow:0 0 24px rgba(151,94,255,.2)}.monitor:after{content:"";position:absolute;inset:0;background:linear-gradient(transparent 48%,rgba(255,255,255,.04) 50%,transparent 52%);background-size:100% 5px}.toast{position:absolute;z-index:40;left:50%;bottom:20px;transform:translate(-50%,20px);opacity:0;background:#130e1c;border:1px solid #563d70;border-radius:99px;padding:9px 13px;font:850 10px ui-monospace,SFMono-Regular,Menlo,monospace;color:#d9c3ff;transition:.22s}.toast.show{transform:translate(-50%,0);opacity:1}
@keyframes shake{25%{transform:translate(7px,-2px)}50%{transform:translate(-6px,3px)}75%{transform:translate(4px,2px)}}@keyframes glitch{20%{transform:translateX(4px) skewX(1deg)}40%{transform:translateX(-5px)}60%{filter:hue-rotate(22deg)}80%{transform:translateY(2px)}}@keyframes flicker{50%{opacity:.4}}@keyframes scan{50%{transform:translateY(2px)}}@keyframes restore{0%{opacity:.35;transform:scale(.94);filter:grayscale(1) blur(1px)}65%{filter:grayscale(.4)}100%{opacity:1;transform:scale(1);filter:none}}@keyframes redpulse{50%{box-shadow:0 12px 0 #330912,0 0 0 7px #16080d,0 0 85px rgba(255,42,88,.62)}}@keyframes press{45%{transform:translateY(10px) scale(.96);box-shadow:0 2px 0 #330912,0 0 0 7px #16080d,0 0 95px rgba(255,42,88,.9)}100%{transform:translateY(0)}}
@media(max-width:760px){body{padding:10px}.top{align-items:flex-start;flex-direction:column}.grid{grid-template-columns:1fr}.controls{position:relative;top:0;order:-1}.buttons{grid-template-columns:repeat(2,1fr)}.stage{min-height:520px}.arena{padding:15px}.roster{grid-template-columns:repeat(2,1fr)}.voteWrap{grid-template-columns:1fr}.ring{margin:auto}.barRow{grid-template-columns:72px 1fr 24px}.monitorGrid{grid-template-columns:repeat(2,1fr)}}
</style>
</head>
<body>
<div id="shell" class="app">
  <div class="top"><div><div class="eyebrow">DWALLET HQ // PRIVATE TEST HARNESS</div><div class="title">ARENA FX LAB</div><div class="sub">Discord Activity preview only. Nothing here changes a real Arena, Telegram group, wallet, score, or database.</div></div><div class="badge">SAFE PREVIEW</div></div>
  <div class="grid">
    <section id="stage" class="stage"><div class="scanlines"></div><div class="stageHeader"><div id="location" class="location">LOCATION // DWALLET HQ</div><div id="sys" class="status">SYSTEM NOMINAL</div></div><div id="arena" class="arena"></div><div id="overlay" class="overlay"></div><div id="toast" class="toast"></div></section>
    <aside class="controls"><h3>Force an effect</h3><p>Replay the flashy rounds without RNG. Use <b>RUN ALL</b> to cycle the whole presentation.</p><div class="buttons">
      <button onclick="fx('normal')">Normal Arena<span class="small">baseline screen</span></button>
      <button onclick="fx('brawl')">💥 HQ Lockdown<span class="small">Mass Brawl</span></button>
      <button onclick="fx('vote')">👁️ Chat Chooses<span class="small">live 30s vote</span></button>
      <button onclick="fx('showdown')">⚔️ Showdown Result<span class="small">top-two 1v1</span></button>
      <button onclick="fx('revival')">⚡ Recovery Protocol<span class="small">Second Chance</span></button>
      <button onclick="fx('crek')">🖥️ Crek's Lair<span class="small">monitor takeover</span></button>
      <button onclick="fx('peach')">🍑 Peach's Button<span class="small">red button gag</span></button>
      <button onclick="fx('glitch')">📡 Rare Glitch<span class="small">HQ anomaly</span></button>
      <button onclick="fx('final')">☠️ Final Five<span class="small">specials disabled</span></button>
      <button class="primary" onclick="runAll()">▶ RUN ALL<span class="small">automatic demo reel</span></button>
    </div><div class="haptic">TELEGRAM HAPTIC PREVIEW: <b id="haptic">IDLE</b><br><span style="color:#776d80">Discord cannot reproduce Telegram's native HapticFeedback; this indicator shows when it would fire.</span></div></aside>
  </div>
</div>
<script>
const shell=document.getElementById('shell'),stage=document.getElementById('stage'),arena=document.getElementById('arena'),overlay=document.getElementById('overlay'),locationEl=document.getElementById('location'),sys=document.getElementById('sys'),hapticEl=document.getElementById('haptic'),toast=document.getElementById('toast');
const names=['SAM','CREK','PEACH','KASS','RUBY','ZERO','WRAITH','MIA','JAX'];let timers=[],voteTimer=null,sequence=false;
function later(fn,ms){const id=setTimeout(fn,ms);timers.push(id);return id}function clearFx(){timers.forEach(clearTimeout);timers=[];if(voteTimer)clearInterval(voteTimer);voteTimer=null;stage.className='stage';overlay.className='overlay';overlay.innerHTML='';locationEl.textContent='LOCATION // DWALLET HQ';sys.textContent='SYSTEM NOMINAL';hapticEl.textContent='IDLE'}
function hap(type){hapticEl.textContent=type.toUpperCase();toast.textContent='TELEGRAM HAPTIC // '+type.toUpperCase();toast.classList.add('show');later(()=>toast.classList.remove('show'),850);try{navigator.vibrate?.(type==='heavy'?[35,20,55]:type==='warning'?[25,25,25]:15)}catch{}}
function roster(out=[]){return '<div class="roster">'+names.map((n,i)=>'<div class="fighter '+(out.includes(n)?'out':i<5?'hot':'')+'"><span>'+n+'</span><span>'+(out.includes(n)?'OUT':'ACTIVE')+'</span></div>').join('')+'</div>'}
function baseline(){arena.innerHTML='<div class="normalCard"><div class="round">ROUND 12</div><div class="headline">DWALLET ARENA</div><div class="copy">A normal round is running. Feature effects stay quiet until the engine actually triggers one.</div>'+roster(['MIA','JAX'])+'</div>'}
function showPanel(kicker,title,sub,body=''){overlay.innerHTML='<div class="fxPanel"><div class="fxKicker">'+kicker+'</div><div class="fxTitle">'+title+'</div><div class="fxSub">'+sub+'</div>'+body+'</div>';overlay.classList.add('show')}
function fx(kind){sequence=false;clearFx();baseline();if(kind==='normal')return;
 if(kind==='brawl'){stage.classList.add('lockdown');locationEl.textContent='LOCATION // DROP CONTROL';sys.textContent='SECURITY OVERRIDE';hap('heavy');showPanel('DWALLET HQ // SECURITY OVERRIDE','HQ LOCKDOWN','MASS BRAWL DETECTED','<div class="chips"><span class="chip">CREK</span><span class="chip">SAM</span><span class="chip">ZERO</span><span class="chip">RUBY</span><span class="chip">PEACH</span></div>');later(()=>{overlay.innerHTML='<div class="fxPanel"><div class="fxKicker warning">IMPACT CASCADE</div><div class="fxTitle">MASS BRAWL</div><div class="chips"><span class="chip live">CREK // SURVIVED</span><span class="chip live">PEACH // SURVIVED</span><span class="chip dead">SAM // ELIMINATED</span><span class="chip dead">ZERO // ELIMINATED</span><span class="chip dead">RUBY // ELIMINATED</span></div></div>';hap('heavy')},1500);later(()=>{overlay.classList.remove('show');arena.innerHTML='<div class="normalCard"><div class="round warning">ROUND 12 // AFTERMATH</div><div class="headline">2 SURVIVORS FROM THE BRAWL</div><div class="copy">HQ unlocks. The rest of Arena resumes.</div>'+roster(['SAM','ZERO','RUBY','MIA','JAX'])+'</div>'},3300)}
 if(kind==='vote'){locationEl.textContent='LOCATION // COMMUNITY FLOOR';sys.textContent='AUDIENCE CONTROL GRANTED';hap('selection');let left=30;showVote(left);voteTimer=setInterval(()=>{left=Math.max(0,left-1);showVote(left);if(left===10)hap('warning');if(left===0){clearInterval(voteTimer);voteTimer=null;hap('heavy');later(()=>fx('showdown'),550)}},1000)}
 if(kind==='showdown'){locationEl.textContent='LOCATION // COMMUNITY FLOOR';sys.textContent='VOTE LOCKED';hap('heavy');showPanel('THE CHAT HAS DECIDED','COMMUNITY SHOWDOWN','TOP TWO LOCKED','<div class="vs"><div class="vsName">CREK</div><div class="vsBadge">VS</div><div class="vsName">PEACH</div></div>');later(()=>{overlay.innerHTML='<div class="fxPanel"><div class="fxKicker good">SHOWDOWN COMPLETE</div><div class="fxTitle">CREK SURVIVES</div><div class="chips"><span class="chip live">CREK // SAFE</span><span class="chip dead">PEACH // ELIMINATED</span></div></div>';hap('success')},1750);later(()=>overlay.classList.remove('show'),3500)}
 if(kind==='revival'){locationEl.textContent='LOCATION // RECOVERY BAY';sys.textContent='RECOVERY PROTOCOL';stage.style.filter='grayscale(.7)';hap('warning');showPanel('DWALLET HQ // RECOVERY PROTOCOL','SECOND CHANCE','TWO ELIMINATED PLAYERS FOUND','<div class="chips restore"><span class="chip dead">RUBY // OUT</span><span class="chip dead">ZERO // OUT</span></div>');later(()=>{stage.style.filter='';overlay.innerHTML='<div class="fxPanel"><div class="fxKicker good">RESTORE COMPLETE</div><div class="fxTitle">RUBY RETURNS</div><div class="chips"><span class="chip live">RUBY // STATUS: ACTIVE</span><span class="chip dead">ZERO // RESTORE FAILED</span></div></div>';hap('success')},2200);later(()=>overlay.classList.remove('show'),4100)}
 if(kind==='crek'){locationEl.textContent="LOCATION // CREK'S LAIR";sys.textContent='MONITOR ARRAY ONLINE';hap('light');showPanel("CREK'S LAIR // CONTROL WALL",'EYES ON EVERYTHING','Arena feeds rerouted to Crek.','<div class="monitorGrid">'+['ARENA 01','CLAIM HALL','BOT BASEMENT','DROP CONTROL','PEACH CAM','PLAYER TRACKING'].map((x,i)=>'<div class="monitor '+(i===4?'hot':'')+'">'+x+(i===4?'<br>CREK ME UP':'<br>FEED ONLINE')+'</div>').join('')+'</div>');later(()=>{sys.textContent='SYSTEM ALERT // CREK ME UP';stage.classList.add('glitching');hap('warning')},1500);later(()=>{stage.classList.remove('glitching');overlay.classList.remove('show')},3200)}
 if(kind==='peach'){locationEl.textContent="LOCATION // PEACH'S LAIR";sys.textContent='BUTTON INTERLOCK ???';showPanel("PEACH'S LAIR",'DO NOT PRESS','This instruction has historically not helped.','<div id="redButton" class="redButton"></div><div class="fxSub">PEACH HAS THE POWER</div>');hap('warning');later(()=>{document.getElementById('redButton')?.classList.add('pressed');stage.classList.add('lockdown');sys.textContent='BUTTON PRESSED // CONSEQUENCES PENDING';hap('heavy')},1700);later(()=>{overlay.innerHTML='<div class="fxPanel"><div class="fxKicker">SYSTEM RESPONSE</div><div class="fxTitle">SON OF A PEACH</div><div class="fxSub">Nobody knows why the button did that.</div></div>'},2300);later(()=>{stage.classList.remove('lockdown');overlay.classList.remove('show')},3900)}
 if(kind==='glitch'){locationEl.textContent='LOCATION // UNKNOWN';sys.textContent='PLAYER COUNT: 10';stage.classList.add('glitching');hap('warning');showPanel('DWALLET HQ // ANOMALY','SIGNAL ERROR','PLAYER COUNT SHOULD BE 9','<div class="chips"><span class="chip">SAM</span><span class="chip">CREK</span><span class="chip">PEACH</span><span class="chip">UNKNOWN_USER</span></div>');later(()=>{sys.textContent='MESSAGE RECEIVED // FROM LATER';overlay.querySelector('.fxSub').textContent='The extra player dot vanished when selected.'},1400);later(()=>{stage.classList.remove('glitching');sys.textContent='SYSTEM NOMINAL // PROBABLY';overlay.classList.remove('show')},3200)}
 if(kind==='final'){stage.classList.add('finalfive');locationEl.textContent='LOCATION // CENTRAL ARENA';sys.textContent='SPECIAL PROTOCOLS DISABLED';hap('heavy');showPanel('DWALLET HQ // ENDGAME','FINAL FIVE','NO REVIVALS. NO CHAT INTERVENTION.','<div class="chips"><span class="chip live">SAM</span><span class="chip live">CREK</span><span class="chip live">PEACH</span><span class="chip live">KASS</span><span class="chip live">RUBY</span></div><div class="fxSub" style="margin-top:18px">Nobody is coming to save you now.</div>');later(()=>{overlay.classList.remove('show');arena.innerHTML='<div class="normalCard"><div class="round">FINAL FIVE // ROUND 18</div><div class="headline">THE HQ CLOSES IN</div><div class="copy">Special rounds are permanently disabled for this Arena. Every elimination from here is final.</div>'+roster(['ZERO','WRAITH','MIA','JAX'])+'</div>'},3000)}
}
function showVote(left){const votes=[9+Math.floor(Math.random()*4),7+Math.floor(Math.random()*4),5+Math.floor(Math.random()*3),3+Math.floor(Math.random()*3)],max=Math.max(...votes);const bars=['CREK','PEACH','SAM','RUBY'].map((n,i)=>'<div class="barRow"><span>'+n+'</span><div class="bar"><i style="width:'+(votes[i]/max*100)+'%"></i></div><b>'+votes[i]+'</b></div>').join('');showPanel('THE CHAT HAS CONTROL','THE CHAT CHOOSES','Spectators and eliminated players control the round.','<div class="voteWrap"><div class="ring" style="--pct:'+(left/30*100)+'"><strong>'+left+'</strong></div><div class="bars">'+bars+'</div></div>')}
async function runAll(){if(sequence)return;sequence=true;const order=[['brawl',4600],['vote',6500],['revival',4800],['crek',3800],['peach',4400],['glitch',3800],['final',4200]];for(const [kind,wait] of order){if(!sequence)break;fx(kind);sequence=true;await new Promise(r=>setTimeout(r,wait))}sequence=false}
baseline();
</script>
</body>
</html>`;
}

export function handleActivityPreview() {
  return new Response(activityPreviewHtml(), {
    headers: {
      "content-type": "text/html; charset=utf-8",
      "cache-control": "no-store",
      "x-content-type-options": "nosniff"
    }
  });
}
