import { InteractionType,InteractionResponseType,verifyDiscordRequest,jsonResponse,interactionMessage,interactionUpdate,button,actionRow,userFromInteraction,registerGuildCommands } from "./discord.js";
import { createGame,addPlayer,removePlayer,startGame,castCrowdVote } from "./core/engine.js";
import { addFakeContestants,setSimulatedCrowd } from "./core/simulation.js";
import { ensureSchema,saveGame,loadGame,loadActiveGameForChannel,getGuildConfig,setGuildTheme } from "./storage.js";
import { getTheme } from "./themes/index.js";
import { FULL_TILT_GUILD_ID,themeForGuild } from "./server-config.js";
export { ArenaCoordinator } from "./coordinator.js";
function playerList(game){const players=Object.values(game.players);if(!players.length)return"Nobody has entered yet.";return players.map((p,i)=>`${i+1}. **${p.displayName}**${p.simulated?" *(sim)*":""}`).join("\n");}
function registrationMessage(game){const theme=getTheme(game.themeId),bits=[];if(game.testMode?.fakeContestants)bits.push("simulated contestants");if(game.testMode?.simulatedCrowd)bits.push("simulated crowd voting");const test=bits.length?`\n\n🧪 **TEST MODE:** ${bits.join(" + ")}`:"";return`# ${theme.labels.arena}\nRegistration is open.\n🎭 **SERVER THEME: ${theme.displayName}**\n\n${playerList(game)}\n\n**${Object.keys(game.players).length} entered**${test}`;}
function registrationComponents(game){return[actionRow(button(`arena:join:${game.id}`,"ENTER ARENA",3,false,"⚔️"),button(`arena:leave:${game.id}`,"LEAVE",2),button(`arena:start:${game.id}`,"START",1,false,"▶️"))];}
function voteSelect(game,page=0){const per=25,total=Math.max(1,Math.ceil(game.aliveIds.length/per)),safe=Math.max(0,Math.min(page,total-1)),ids=game.aliveIds.slice(safe*per,(safe+1)*per);const select={type:3,custom_id:`arena:vote_cast:${game.id}:${safe}`,placeholder:"Choose a player...",min_values:1,max_values:1,options:ids.map(id=>({label:game.players[id]?.displayName?.slice(0,100)||"Unknown",value:id}))};const rows=[{type:1,components:[select]}];if(total>1)rows.push(actionRow(button(`arena:vote_open:${game.id}:${safe-1}`,"PREV",2,safe===0),button(`arena:vote_open:${game.id}:${safe+1}`,"NEXT",2,safe>=total-1)));return{rows,page:safe,totalPages:total};}
async function kickCoordinator(env,channelId,action="kick"){if(!env.ARENA_COORDINATOR)return;const id=env.ARENA_COORDINATOR.idFromName(channelId),stub=env.ARENA_COORDINATOR.get(id);await stub.fetch("https://arena.internal/",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({action,channelId})});}
async function handleArenaCommand(interaction,env){if(!interaction.guild_id)return interactionMessage("Arena can only run inside a server.",[],true);if(!env.DB)return interactionMessage("Arena database is not configured yet.",[],true);await ensureSchema(env.DB);const option=interaction.data?.options?.[0],sub=option?.name||"status",channelId=interaction.channel_id,guildId=interaction.guild_id,user=userFromInteraction(interaction);let game=await loadActiveGameForChannel(env.DB,channelId);
if(sub==="start"){if(game)return interactionMessage("There is already an Arena game active in this channel.",[],true);const config=await getGuildConfig(env.DB,guildId),themeId=themeForGuild(guildId,config.theme_id);if(themeId!==config.theme_id)await setGuildTheme(env.DB,guildId,themeId);game=createGame({guildId,channelId,hostId:user.id,themeId});addPlayer(game,user);await saveGame(env.DB,game);return interactionMessage(registrationMessage(game),registrationComponents(game));}
if(sub==="cancel"){if(!game)return interactionMessage("There is no active Arena game here.",[],true);if(game.hostId!==user.id)return interactionMessage("Only the Arena host can cancel this game.",[],true);game.status="cancelled";await saveGame(env.DB,game);return interactionMessage("Arena cancelled.",[],true);}
if(sub==="testfill"){if(!game)return interactionMessage("Start an Arena lobby first with `/arena start`.",[],true);if(game.hostId!==user.id)return interactionMessage("Only the Arena host can use test mode.",[],true);if(game.status!=="registration")return interactionMessage("Fake contestants can only be added before the match starts.",[],true);const count=option?.options?.find(x=>x.name==="count")?.value??20,added=addFakeContestants(game,count);await saveGame(env.DB,game);return interactionMessage(`🧪 Added **${added.length} simulated contestants**. The lobby now has **${game.aliveIds.length} players**.`,[],true);}
if(sub==="testcrowd"){if(!game)return interactionMessage("Start an Arena lobby first with `/arena start`.",[],true);if(game.hostId!==user.id)return interactionMessage("Only the Arena host can use test mode.",[],true);const enabled=Boolean(option?.options?.find(x=>x.name==="enabled")?.value);setSimulatedCrowd(game,enabled);await saveGame(env.DB,game);return interactionMessage(`🧪 Simulated crowd voting is now **${enabled?"ON":"OFF"}**.`,[],true);}
if(!game)return interactionMessage("There is no active Arena game in this channel.",[],true);return interactionMessage(`**Arena status**\nTheme: **${getTheme(game.themeId).displayName}**\nRound: **${game.round}**\nAlive: **${game.aliveIds.length}**\nEliminated: **${game.eliminatedIds.length}**\nStatus: **${game.status}**`,[],true);}
async function handleComponent(interaction,env){const parts=(interaction.data?.custom_id||"").split(":"),action=parts[1],gameId=parts[2],user=userFromInteraction(interaction);if(!gameId||!user||!env.DB)return interactionMessage("Arena couldn't read that action.",[],true);await ensureSchema(env.DB);const game=await loadGame(env.DB,gameId);if(!game)return interactionMessage("That Arena game no longer exists.",[],true);
if(action==="join"){try{addPlayer(game,user);await saveGame(env.DB,game);return interactionUpdate(registrationMessage(game),registrationComponents(game));}catch(e){return interactionMessage(e.message,[],true);}}
if(action==="leave"){try{removePlayer(game,user.id);await saveGame(env.DB,game);return interactionUpdate(registrationMessage(game),registrationComponents(game));}catch(e){return interactionMessage(e.message,[],true);}}
if(action==="start"){if(user.id!==game.hostId)return interactionMessage("Only the Arena host can start the game.",[],true);try{startGame(game);await saveGame(env.DB,game);await kickCoordinator(env,game.channelId,"kick");const theme=getTheme(game.themeId),sim=game.testMode?.simulatedCrowd?"\n🧪 Simulated spectators are watching too.":"";return interactionUpdate(`# ${theme.labels.arena}\nThe doors close. **${game.aliveIds.length} players** are inside.${sim}\n\nThe first round begins now.`,[]);}catch(e){return interactionMessage(e.message,[],true);}}
if(action==="vote_open"){if(!game.crowdVote||game.crowdVote.status!=="open")return interactionMessage("The audience vote is closed.",[],true);if(game.aliveIds.includes(user.id))return interactionMessage("You're still fighting. The audience gets this vote.",[],true);const {rows,page,totalPages}=voteSelect(game,Number(parts[3]||0)),voteName=game.themeId==="full_tilt"?"Final Bet":"Final Scare";return interactionMessage(`**Choose who enters the ${voteName}.**\nPage ${page+1}/${totalPages}\nYou may change your vote until voting closes.`,rows,true);}
if(action==="vote_cast"){if(!game.crowdVote||game.crowdVote.status!=="open")return interactionMessage("The audience vote is closed.",[],true);if(game.aliveIds.includes(user.id))return interactionMessage("You're still fighting. The audience gets this vote.",[],true);const id=interaction.data?.values?.[0];try{castCrowdVote(game,user.id,id);await saveGame(env.DB,game);return interactionMessage(`Vote locked on **${game.players[id]?.displayName||"Unknown"}**. You can change it before time runs out.`,[],true);}catch(e){return interactionMessage(e.message,[],true);}}
return interactionMessage("Unknown Arena action.",[],true);}
async function handleDiscord(request,env){const raw=await request.text();if(!await verifyDiscordRequest(request,env.DISCORD_PUBLIC_KEY,raw))return new Response("Bad signature",{status:401});const i=JSON.parse(raw);if(i.type===InteractionType.PING)return jsonResponse({type:InteractionResponseType.PONG});if(i.type===InteractionType.APPLICATION_COMMAND&&i.data?.name==="arena")return handleArenaCommand(i,env);if(i.type===InteractionType.MESSAGE_COMPONENT&&i.data?.custom_id?.startsWith("arena:"))return handleComponent(i,env);return interactionMessage("Veil doesn't know that Arena action yet.",[],true);}
async function handleRegister(request,env){const provided=request.headers.get("x-admin-secret");if(!env.ADMIN_SECRET||provided!==env.ADMIN_SECRET)return new Response("Unauthorized",{status:401});if(!env.DISCORD_APPLICATION_ID||!env.DISCORD_BOT_TOKEN)return jsonResponse({ok:false,error:"Discord credentials missing"},500);if(!env.DB)return jsonResponse({ok:false,error:"Arena database missing"},500);await ensureSchema(env.DB);const body=await request.json().catch(()=>({}));if(!body.guildId)return jsonResponse({ok:false,error:"guildId required"},400);const themeId=themeForGuild(body.guildId,body.themeId||"vibe_queen_slots");const commands=await registerGuildCommands(env.DISCORD_APPLICATION_ID,body.guildId,env.DISCORD_BOT_TOKEN);await setGuildTheme(env.DB,body.guildId,themeId);return jsonResponse({ok:true,themeId,commands});}
function setupPage(){return`<!doctype html><html><head><meta name="viewport" content="width=device-width,initial-scale=1"><title>Full Tilt Arena Setup</title><style>body{font-family:system-ui;margin:0;background:#111;color:#fff;display:grid;place-items:center;min-height:100vh}.card{width:min(92vw,460px);background:#1c1c1c;padding:24px;border-radius:18px}input,button{width:100%;box-sizing:border-box;padding:14px;border-radius:10px;font-size:16px}input{margin:12px 0;background:#0d0d0d;color:#fff;border:1px solid #444}button{border:0;font-weight:700}#out{white-space:pre-wrap;margin-top:14px;color:#ddd}</style></head><body><div class="card"><h1>Full Tilt Arena</h1><p>Enter the Cloudflare ADMIN_SECRET you already know. It is sent directly to your Arena Worker and is not stored by this page.</p><input id="secret" type="password" placeholder="ADMIN_SECRET"><button id="go">REGISTER /arena</button><div id="out"></div></div><script>go.onclick=async()=>{out.textContent='Registering…';try{const r=await fetch('/admin/register',{method:'POST',headers:{'content-type':'application/json','x-admin-secret':secret.value},body:JSON.stringify({guildId:'${FULL_TILT_GUILD_ID}',themeId:'full_tilt'})});const text=await r.text();out.textContent=r.ok?'✅ Done. Go back to Full Tilt and type /arena.':'❌ '+r.status+' '+text}catch(e){out.textContent='❌ '+e.message}}</script></body></html>`;}
export default{async fetch(request,env){const url=new URL(request.url);if(url.pathname==="/health")return jsonResponse({ok:true,service:"veil-arena",status:"ready",database:Boolean(env.DB),coordinator:Boolean(env.ARENA_COORDINATOR),discordConfigured:Boolean(env.DISCORD_PUBLIC_KEY&&env.DISCORD_BOT_TOKEN&&env.DISCORD_APPLICATION_ID)});if(url.pathname==="/setup/full-tilt"&&request.method==="GET")return new Response(setupPage(),{headers:{"content-type":"text/html; charset=utf-8","cache-control":"no-store"}});if(url.pathname==="/interactions"&&request.method==="POST")return handleDiscord(request,env);if(url.pathname==="/admin/register"&&request.method==="POST")return handleRegister(request,env);return new Response("Veil Arena is online.",{headers:{"content-type":"text/plain; charset=utf-8"}});}};
