import { InteractionType,InteractionResponseType,verifyDiscordRequest,jsonResponse,interactionMessage,interactionUpdate,button,actionRow,userFromInteraction,registerGuildCommands,createChannelMessage,createChannelTextFile } from "./discord.js";
import { createGame,addPlayer,removePlayer,startGame,castCrowdVote } from "./core/engine.js";
import { ensureSchema,saveGame,loadGame,loadActiveGameForChannel,loadFinishedGameForGuild,getGuildConfig,setGuildTheme,loadPlayerStats,loadArenaLeaderboard } from "./storage.js";
import { getTheme } from "./themes/index.js";
import { rulesForTheme } from "./rules.js";
import { FULL_TILT_GUILD_ID,VIBE_QUEEN_GUILD_ID,themeForGuild } from "./server-config.js";
import { buildArenaLog } from "./logs.js";
import {
  userFromTelegram,
  sendTelegramMessage,
  configureTelegramBot,
  telegramWebhookAuthorized,
  telegramArenaLaunchUrl,
  telegramArenaLauncherKeyboard
} from "./telegram.js";
import { getArenaCooldownRemaining,formatCooldown } from "./cooldown.js";
import { miniAppHtml,handleMiniAppState,handleMiniAppAction } from "./miniapp.js";
export { ArenaCoordinator } from "./coordinator.js";

function playerList(game){const players=Object.values(game.players);if(!players.length)return"Nobody has entered yet.";return players.map((p,i)=>`${i+1}. **${p.displayName}**`).join("\n");}
function registrationMessage(game){const theme=getTheme(game.themeId);return`# ${theme.labels.arena}\nRegistration is open.\n🎭 **SERVER THEME: ${theme.displayName}**\n\n${playerList(game)}\n\n**${Object.keys(game.players).length} entered**`;}
function registrationComponents(game){return[actionRow(button(`arena:join:${game.id}`,"ENTER ARENA",3,false,"⚔️"),button(`arena:leave:${game.id}`,"LEAVE",2),button(`arena:start:${game.id}`,"START",1,false,"▶️"))];}
function voteSelect(game,page=0){const per=25,total=Math.max(1,Math.ceil(game.aliveIds.length/per)),safe=Math.max(0,Math.min(page,total-1)),ids=game.aliveIds.slice(safe*per,(safe+1)*per);const select={type:3,custom_id:`arena:vote_cast:${game.id}:${safe}`,placeholder:"Choose a player...",min_values:1,max_values:1,options:ids.map(id=>({label:game.players[id]?.displayName?.slice(0,100)||"Unknown",value:id}))};const rows=[{type:1,components:[select]}];if(total>1)rows.push(actionRow(button(`arena:vote_open:${game.id}:${safe-1}`,"PREV",2,safe===0),button(`arena:vote_open:${game.id}:${safe+1}`,"NEXT",2,safe>=total-1)));return{rows,page:safe,totalPages:total};}
export async function kickCoordinator(env,channelId,action="kick",platform="discord"){if(!env.ARENA_COORDINATOR)return;const id=env.ARENA_COORDINATOR.idFromName(channelId),stub=env.ARENA_COORDINATOR.get(id);await stub.fetch("https://arena.internal/",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({action,channelId,platform})});}
async function scheduleMessageDelete(env,channelId,messageId,delayMs=30000,platform="discord"){if(!env.ARENA_COORDINATOR||!messageId)return;const id=env.ARENA_COORDINATOR.idFromName(`delete:${platform}:${messageId}`),stub=env.ARENA_COORDINATOR.get(id);await stub.fetch("https://arena.internal/",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({action:"delete_message",channelId,messageId,delayMs,platform})});}
async function themeIdForGuild(env,guildId){const config=await getGuildConfig(env.DB,guildId),themeId=themeForGuild(guildId,config.theme_id);if(themeId!==config.theme_id)await setGuildTheme(env.DB,guildId,themeId);return themeId;}

async function handleArenaCommand(interaction,env){
  if(!interaction.guild_id)return interactionMessage("Arena can only run inside a server.",[],true);
  if(!env.DB)return interactionMessage("Arena database is not configured yet.",[],true);
  await ensureSchema(env.DB);
  const option=interaction.data?.options?.[0],sub=option?.name||"start",channelId=interaction.channel_id,guildId=interaction.guild_id,user=userFromInteraction(interaction);
  if(sub==="rules"){const themeId=await themeIdForGuild(env,guildId);const posted=await createChannelMessage(channelId,env.DISCORD_BOT_TOKEN,{content:rulesForTheme(themeId)});await scheduleMessageDelete(env,channelId,posted?.id,30000,"discord");return interactionMessage("📜 Arena rules posted for **30 seconds**.",[],true);}
  let game=await loadActiveGameForChannel(env.DB,channelId);
  if(sub==="start"){if(game)return interactionMessage("There is already an Arena game active in this channel.",[],true);const themeId=await themeIdForGuild(env,guildId);game=createGame({guildId,channelId,hostId:user.id,themeId,platform:"discord"});addPlayer(game,user);await saveGame(env.DB,game);return interactionMessage(registrationMessage(game),registrationComponents(game));}
  return interactionMessage("Unknown Arena command.",[],true);
}

function statsText(user,stats){const games=stats?.games_played||0,wins=stats?.wins||0,kills=stats?.total_kills||0,revives=stats?.total_revivals||0,best=stats?.max_kills_single_game||0,crowd=stats?.crowd_survivals||0,rate=games?((wins/games)*100).toFixed(1):"0.0";return`# ⚔️ ${user.displayName}'S ARENA STATS\n\n**Arenas Played:** ${games}\n**Wins:** ${wins}\n**Total Kills:** ${kills}\n**Total Revivals:** ${revives}\n**Most Kills in One Arena:** ${best}\n**Crowd Votes Survived:** ${crowd}\n**Win Rate:** ${rate}%\n\n*Stats track from Arena's official launch in this server.*`;}
async function handleStatsCommand(interaction,env){if(!interaction.guild_id)return interactionMessage("Arena stats only exist inside a server.",[],true);if(!env.DB)return interactionMessage("Arena database is not configured yet.",[],true);await ensureSchema(env.DB);const user=userFromInteraction(interaction),stats=await loadPlayerStats(env.DB,interaction.guild_id,user.id);return interactionMessage(statsText(user,stats));}
function boardSection(title,rows){if(!rows?.length)return`**${title}**\nNo records yet.`;return`**${title}**\n${rows.map((r,i)=>`${i+1}. ${r.display_name} — **${r.value}**`).join("\n")}`;}
async function handleLeaderboardCommand(interaction,env){if(!interaction.guild_id)return interactionMessage("Arena leaderboards only exist inside a server.",[],true);if(!env.DB)return interactionMessage("Arena database is not configured yet.",[],true);await ensureSchema(env.DB);const b=await loadArenaLeaderboard(env.DB,interaction.guild_id,5);const content=["# 🏆 ARENA LEADERBOARD",boardSection("⚔️ MOST ARENAS PLAYED",b.gamesPlayed),boardSection("👑 MOST WINS",b.wins),boardSection("💀 TOTAL KILLS",b.kills),boardSection("🕯️ TOTAL REVIVALS",b.revivals),boardSection("🔥 MOST KILLS IN ONE ARENA",b.singleGameKills),boardSection("👁️ CROWD VOTES SURVIVED",b.crowdSurvivals)].join("\n\n");return interactionMessage(content);}
async function handleLogCommand(interaction,env){if(!interaction.guild_id)return interactionMessage("Arena logs only exist inside a server.",[],true);if(!env.DB)return interactionMessage("Arena database is not configured yet.",[],true);await ensureSchema(env.DB);const requested=Math.max(1,Number(interaction.data?.options?.find(x=>x.name==="match")?.value||1));const game=await loadFinishedGameForGuild(env.DB,interaction.guild_id,requested-1);if(!game)return interactionMessage(`I couldn't find completed Arena match #${requested} for this server.`,[],true);const log=buildArenaLog(game,requested),filename=`arena-match-${requested}-${game.id.slice(0,8)}.txt`;await createChannelTextFile(interaction.channel_id,env.DISCORD_BOT_TOKEN,filename,log,`📜 **Arena Match ${requested} narration log**`);return interactionMessage(`Done — I posted **Arena Match ${requested}** as a text file in this channel.\n\nUse \`/arenalog match:2\` for the previous match, \`match:3\` for the one before that, etc.`,[],true);}
async function handleComponent(interaction,env){const parts=(interaction.data?.custom_id||"").split(":"),action=parts[1],gameId=parts[2],user=userFromInteraction(interaction);if(!gameId||!user||!env.DB)return interactionMessage("Arena couldn't read that action.",[],true);await ensureSchema(env.DB);const game=await loadGame(env.DB,gameId);if(!game)return interactionMessage("That Arena game no longer exists.",[],true);if(action==="join"){try{addPlayer(game,user);await saveGame(env.DB,game);return interactionUpdate(registrationMessage(game),registrationComponents(game));}catch(e){return interactionMessage(e.message,[],true);}}if(action==="leave"){try{removePlayer(game,user.id);await saveGame(env.DB,game);return interactionUpdate(registrationMessage(game),registrationComponents(game));}catch(e){return interactionMessage(e.message,[],true);}}if(action==="start"){if(user.id!==game.hostId)return interactionMessage("Only the Arena host can start the game.",[],true);try{startGame(game);await saveGame(env.DB,game);await kickCoordinator(env,game.channelId,"kick","discord");const theme=getTheme(game.themeId);return interactionUpdate(`# ${theme.labels.arena}\nThe doors close. **${game.aliveIds.length} players** are inside.\n\nThe first round begins now.`,[]);}catch(e){return interactionMessage(e.message,[],true);}}if(action==="vote_open"){if(!game.crowdVote||game.crowdVote.status!=="open")return interactionMessage("The audience vote is closed.",[],true);if(game.aliveIds.includes(user.id))return interactionMessage("You're still fighting. The audience gets this vote.",[],true);const {rows,page,totalPages}=voteSelect(game,Number(parts[3]||0)),voteName=game.themeId==="full_tilt"?"Final Bet":"Final Scare";return interactionMessage(`**Choose who enters the ${voteName}.**\nPage ${page+1}/${totalPages}\nYou may change your vote until voting closes.`,rows,true);}if(action==="vote_cast"){if(!game.crowdVote||game.crowdVote.status!=="open")return interactionMessage("The audience vote is closed.",[],true);if(game.aliveIds.includes(user.id))return interactionMessage("You're still fighting. The audience gets this vote.",[],true);const id=interaction.data?.values?.[0];try{castCrowdVote(game,user.id,id);await saveGame(env.DB,game);return interactionMessage(`Vote locked on **${game.players[id]?.displayName||"Unknown"}**. You can change it before time runs out.`,[],true);}catch(e){return interactionMessage(e.message,[],true);}}return interactionMessage("Unknown Arena action.",[],true);}
async function handleDiscord(request,env){const raw=await request.text();if(!await verifyDiscordRequest(request,env.DISCORD_PUBLIC_KEY,raw))return new Response("Bad signature",{status:401});const i=JSON.parse(raw);if(i.type===InteractionType.PING)return jsonResponse({type:InteractionResponseType.PONG});if(i.type===InteractionType.APPLICATION_COMMAND){if(i.data?.name==="arena")return handleArenaCommand(i,env);if(i.data?.name==="arenastats")return handleStatsCommand(i,env);if(i.data?.name==="arenaleaderboard")return handleLeaderboardCommand(i,env);if(i.data?.name==="arenalog")return handleLogCommand(i,env);}if(i.type===InteractionType.MESSAGE_COMPONENT&&i.data?.custom_id?.startsWith("arena:"))return handleComponent(i,env);return interactionMessage("Veil doesn't know that Arena action yet.",[],true);}

function telegramScope(chatId){return`tg:${chatId}`;}
function telegramCommand(text=""){const first=String(text).trim().split(/\s+/)[0]||"";return first.toLowerCase().split("@")[0];}
function telegramArgs(text=""){return String(text).trim().split(/\s+/).slice(1);}
function telegramGroup(chat){return chat?.type==="group"||chat?.type==="supergroup";}
function telegramStatsText(user,stats){return statsText(user,stats).replace("in this server","in this Telegram group");}
function telegramLeaderboardText(b){return["# 🏆 DWALLET ARENA LEADERBOARD",boardSection("⚔️ MOST ARENAS PLAYED",b.gamesPlayed),boardSection("👑 MOST WINS",b.wins),boardSection("💀 TOTAL KILLS",b.kills),boardSection("🕯️ TOTAL REVIVALS",b.revivals),boardSection("🔥 MOST KILLS IN ONE ARENA",b.singleGameKills),boardSection("👁️ CROWD VOTES SURVIVED",b.crowdSurvivals)].join("\n\n");}

async function telegramStartArena(message,env){
  const chat=message.chat,user=userFromTelegram(message.from);
  if(!telegramGroup(chat))return sendTelegramMessage(String(chat.id),env.TELEGRAM_BOT_TOKEN,{text:"Arena can only run inside a Telegram group or supergroup."});
  if(!user)return null;
  await ensureSchema(env.DB);
  const channelId=telegramScope(chat.id),guildId=channelId;
  const active=await loadActiveGameForChannel(env.DB,channelId);
  if(active){
    const controls=active.telegramLaunchUrl?telegramArenaLauncherKeyboard(active.telegramLaunchUrl,"⚔️ OPEN ACTIVE ARENA"):undefined;
    return sendTelegramMessage(channelId,env.TELEGRAM_BOT_TOKEN,{text:"💜 There is already a DWallet Arena active in this group.",reply_markup:controls});
  }
  const remaining=await getArenaCooldownRemaining(env.DB,channelId);
  if(remaining>0)return sendTelegramMessage(channelId,env.TELEGRAM_BOT_TOKEN,{text:`⏳ DWallet Arena is cooling down. Try again in **${formatCooldown(remaining)}**.`});
  const game=createGame({guildId,channelId,hostId:user.id,themeId:"dwallet",platform:"telegram"});
  addPlayer(game,user);
  await saveGame(env.DB,game);
  const launchUrl=await telegramArenaLaunchUrl(env.TELEGRAM_BOT_TOKEN,game.id);
  const posted=await sendTelegramMessage(channelId,env.TELEGRAM_BOT_TOKEN,{
    text:`# 💜 DWALLET ARENA\nRegistration is open. **${user.displayName}** is hosting.\n\nTap below to enter the Arena window. **All rounds, eliminations, revivals and votes happen inside the Mini App** so this chat stays clean.`,
    reply_markup:telegramArenaLauncherKeyboard(launchUrl)
  });
  game.telegramLaunchUrl=launchUrl;
  game.telegramLauncherMessageId=posted?.id||null;
  await saveGame(env.DB,game);
  return posted;
}

async function telegramRules(message,env){const chat=message.chat;if(!telegramGroup(chat))return sendTelegramMessage(String(chat.id),env.TELEGRAM_BOT_TOKEN,{text:"Arena rules are meant for a Telegram group where Arena can run."});return sendTelegramMessage(telegramScope(chat.id),env.TELEGRAM_BOT_TOKEN,{text:rulesForTheme("dwallet")});}
async function telegramStats(message,env){const chat=message.chat,user=userFromTelegram(message.from);if(!telegramGroup(chat))return sendTelegramMessage(String(chat.id),env.TELEGRAM_BOT_TOKEN,{text:"Arena stats are tracked inside Telegram groups."});if(!user)return null;await ensureSchema(env.DB);const guildId=telegramScope(chat.id),stats=await loadPlayerStats(env.DB,guildId,user.id);return sendTelegramMessage(guildId,env.TELEGRAM_BOT_TOKEN,{text:telegramStatsText(user,stats)});}
async function telegramLeaderboard(message,env){const chat=message.chat;if(!telegramGroup(chat))return sendTelegramMessage(String(chat.id),env.TELEGRAM_BOT_TOKEN,{text:"Arena leaderboards are tracked inside Telegram groups."});await ensureSchema(env.DB);const guildId=telegramScope(chat.id),board=await loadArenaLeaderboard(env.DB,guildId,5);return sendTelegramMessage(guildId,env.TELEGRAM_BOT_TOKEN,{text:telegramLeaderboardText(board)});}
async function handleTelegramMessage(message,env){const cmd=telegramCommand(message?.text||"");if(cmd==="/arena"){const sub=(telegramArgs(message.text)[0]||"").toLowerCase();if(sub==="rules")return telegramRules(message,env);if(!sub||sub==="start")return telegramStartArena(message,env);return sendTelegramMessage(telegramScope(message.chat.id),env.TELEGRAM_BOT_TOKEN,{text:"Use `/arena` to start or `/arena rules` for the rules."});}if(cmd==="/arenastats")return telegramStats(message,env);if(cmd==="/arenaleaderboard")return telegramLeaderboard(message,env);return null;}
async function handleTelegram(request,env){if(!env.TELEGRAM_BOT_TOKEN||!env.TELEGRAM_WEBHOOK_SECRET)return new Response("Telegram is not configured",{status:503});if(!telegramWebhookAuthorized(request,env.TELEGRAM_WEBHOOK_SECRET))return new Response("Bad Telegram webhook secret",{status:401});if(!env.DB)return new Response("Arena database missing",{status:503});const update=await request.json().catch(()=>null);if(!update)return new Response("Bad update",{status:400});if(update.message?.text)await handleTelegramMessage(update.message,env);return jsonResponse({ok:true});}

async function handleRegister(request,env){const provided=request.headers.get("x-admin-secret");if(!env.ADMIN_SECRET||provided!==env.ADMIN_SECRET)return new Response("Unauthorized",{status:401});if(!env.DISCORD_APPLICATION_ID||!env.DISCORD_BOT_TOKEN)return jsonResponse({ok:false,error:"Discord credentials missing"},500);if(!env.DB)return jsonResponse({ok:false,error:"Arena database missing"},500);await ensureSchema(env.DB);const body=await request.json().catch(()=>({}));if(!body.guildId)return jsonResponse({ok:false,error:"guildId required"},400);const themeId=themeForGuild(body.guildId,body.themeId||"vibe_queen_slots");const commands=await registerGuildCommands(env.DISCORD_APPLICATION_ID,body.guildId,env.DISCORD_BOT_TOKEN);await setGuildTheme(env.DB,body.guildId,themeId);return jsonResponse({ok:true,themeId,commands});}
function escapeHtml(value=""){return String(value).replace(/[&<>"']/g,ch=>({"&":"&amp;","<":"&lt;",">":"&gt;","\"":"&quot;","'":"&#39;"}[ch]));}
function telegramSetupResultPage({ok,message,miniAppUrl,botUsername}){const title=ok?"✅ Telegram registered":"❌ Telegram setup failed";const detail=escapeHtml(message||"");const bot=botUsername?`<p>Bot: <b>@${escapeHtml(botUsername)}</b></p>`:"";const app=miniAppUrl?`<p>Mini App:</p><div class="url">${escapeHtml(miniAppUrl)}</div>`:"";return`<!doctype html><html><head><meta name="viewport" content="width=device-width,initial-scale=1"><title>${title}</title><style>body{font-family:system-ui;margin:0;background:#111;color:#fff;display:grid;place-items:center;min-height:100vh}.card{width:min(92vw,560px);background:#1c1c1c;padding:24px;border-radius:18px}.url{word-break:break-all;background:#0d0d0d;padding:10px;border-radius:10px;color:#cdb3ff}a{color:#cdb3ff}</style></head><body><div class="card"><h1>${title}</h1>${bot}${app}<p>${detail}</p><p><a href="/setup/telegram?v=form-v1">Back to setup</a></p></div></body></html>`;}
async function handleTelegramRegister(request,env){const contentType=request.headers.get("content-type")||"";let provided=request.headers.get("x-admin-secret")||"";let htmlResponse=false;if(!provided&&contentType.includes("application/x-www-form-urlencoded")){const form=await request.formData().catch(()=>null);provided=String(form?.get("adminSecret")||"");htmlResponse=true;}const respond=(payload,status=200)=>htmlResponse?new Response(telegramSetupResultPage({ok:status>=200&&status<300,message:payload.error||payload.message||"",miniAppUrl:payload.miniAppUrl||null,botUsername:payload.botUsername||null}),{status,headers:{"content-type":"text/html; charset=utf-8","cache-control":"no-store"}}):jsonResponse(payload,status);if(!env.ADMIN_SECRET||provided!==env.ADMIN_SECRET)return respond({ok:false,error:"ADMIN_SECRET is missing or does not match."},401);if(!env.TELEGRAM_BOT_TOKEN||!env.TELEGRAM_WEBHOOK_SECRET)return respond({ok:false,error:"Telegram credentials missing. Check TELEGRAM_BOT_TOKEN and TELEGRAM_WEBHOOK_SECRET in Cloudflare."},500);if(!env.DB)return respond({ok:false,error:"Arena database missing"},500);await ensureSchema(env.DB);const origin=new URL(request.url).origin,webhookUrl=`${origin}/telegram/webhook`,miniAppUrl=`${origin}/telegram/arena`;try{const bot=await configureTelegramBot(env.TELEGRAM_BOT_TOKEN,webhookUrl,env.TELEGRAM_WEBHOOK_SECRET);return respond({ok:true,themeId:"dwallet",botUsername:bot?.username||null,webhookUrl,miniAppUrl,commands:["arena","arenastats","arenaleaderboard"],message:"Webhook and Telegram commands are registered. Add Veil to the DWallet group, make it an admin, and run /arena."});}catch(error){return respond({ok:false,error:String(error?.message||error)},502);}}
function setupPage({title,guildId,themeId,doneText}){return`<!doctype html><html><head><meta name="viewport" content="width=device-width,initial-scale=1"><title>${title} Arena Setup</title><style>body{font-family:system-ui;margin:0;background:#111;color:#fff;display:grid;place-items:center;min-height:100vh}.card{width:min(92vw,460px);background:#1c1c1c;padding:24px;border-radius:18px}input,button{width:100%;box-sizing:border-box;padding:14px;border-radius:10px;font-size:16px}input{margin:12px 0;background:#0d0d0d;color:#fff;border:1px solid #444}button{border:0;font-weight:700}#out{white-space:pre-wrap;margin-top:14px;color:#ddd}</style></head><body><div class="card"><h1>${title} Arena</h1><p>Enter the Cloudflare ADMIN_SECRET you already know. It is sent directly to your Arena Worker and is not stored by this page.</p><input id="secret" type="password" placeholder="ADMIN_SECRET"><button id="go" type="button">REGISTER ARENA</button><div id="out"></div></div><script>(()=>{const go=document.getElementById('go'),out=document.getElementById('out'),secret=document.getElementById('secret');go.addEventListener('click',async()=>{const value=secret.value.trim();if(!value){out.textContent='❌ Enter ADMIN_SECRET first.';return;}go.disabled=true;out.textContent='Registering…';try{const r=await fetch('/admin/register',{method:'POST',headers:{'content-type':'application/json','x-admin-secret':value},body:JSON.stringify({guildId:'${guildId}',themeId:'${themeId}'})});const text=await r.text();out.textContent=r.ok?'✅ ${doneText}':'❌ '+r.status+' '+text}catch(e){out.textContent='❌ '+e.message}finally{go.disabled=false;}});})();</script></body></html>`;}
function telegramSetupPage(origin){const appUrl=`${origin}/telegram/arena`;return`<!doctype html><html><head><meta name="viewport" content="width=device-width,initial-scale=1"><title>DWallet Telegram Arena Setup</title><style>body{font-family:system-ui;margin:0;background:#111;color:#fff;display:grid;place-items:center;min-height:100vh}.card{width:min(92vw,560px);background:#1c1c1c;padding:24px;border-radius:18px}input,button{width:100%;box-sizing:border-box;padding:14px;border-radius:10px;font-size:16px}input{margin:12px 0;background:#0d0d0d;color:#fff;border:1px solid #444}button{border:0;font-weight:700}.url{word-break:break-all;background:#0d0d0d;padding:10px;border-radius:10px;color:#cdb3ff}.build{margin-top:18px;color:#888;font-size:12px}</style></head><body><div class="card"><h1>💜 DWallet Telegram Arena</h1><p>1. Make sure TELEGRAM_BOT_TOKEN and TELEGRAM_WEBHOOK_SECRET are Worker secrets.</p><p>2. In BotFather: <b>/mybots → Veil → Bot Settings → Configure Mini App → Enable Mini App</b>, then use this as the Main Mini App URL:</p><div class="url">${appUrl}</div><p>3. Register Veil's webhook and commands here:</p><form method="post" action="/admin/telegram/register"><input name="adminSecret" type="password" placeholder="ADMIN_SECRET" required autocomplete="current-password"><button type="submit">REGISTER TELEGRAM</button></form><p class="build">Setup build: telegram-form-v1</p></div></body></html>`;}

export default{async fetch(request,env){const url=new URL(request.url);if(url.pathname==="/health")return jsonResponse({ok:true,service:"veil-arena",status:"ready",build:"telegram-form-v1",database:Boolean(env.DB),coordinator:Boolean(env.ARENA_COORDINATOR),discordConfigured:Boolean(env.DISCORD_PUBLIC_KEY&&env.DISCORD_BOT_TOKEN&&env.DISCORD_APPLICATION_ID),telegramConfigured:Boolean(env.TELEGRAM_BOT_TOKEN&&env.TELEGRAM_WEBHOOK_SECRET),miniApp:true});if(url.pathname==="/setup/full-tilt"&&request.method==="GET")return new Response(setupPage({title:"Full Tilt",guildId:FULL_TILT_GUILD_ID,themeId:"full_tilt",doneText:"Done. Go back to Full Tilt and type /arena."}),{headers:{"content-type":"text/html; charset=utf-8","cache-control":"no-store"}});if(url.pathname==="/setup/vibe-queen"&&request.method==="GET")return new Response(setupPage({title:"Vibe Queen Slots: After Dark",guildId:VIBE_QUEEN_GUILD_ID,themeId:"vibe_queen_slots",doneText:"Done. Go back to Vibe Queen Slots and type /arena."}),{headers:{"content-type":"text/html; charset=utf-8","cache-control":"no-store"}});if(url.pathname==="/setup/telegram"&&request.method==="GET")return new Response(telegramSetupPage(url.origin),{headers:{"content-type":"text/html; charset=utf-8","cache-control":"no-store"}});if(url.pathname==="/telegram/arena"&&request.method==="GET")return new Response(miniAppHtml(),{headers:{"content-type":"text/html; charset=utf-8","cache-control":"no-store","content-security-policy":"default-src 'self' https://telegram.org; script-src 'self' 'unsafe-inline' https://telegram.org; style-src 'self' 'unsafe-inline'; connect-src 'self'; img-src 'self' data: https:; frame-ancestors https://web.telegram.org https://*.telegram.org"}});if(url.pathname==="/telegram/miniapp/state"&&request.method==="GET")return handleMiniAppState(request,env);if(url.pathname==="/telegram/miniapp/action"&&request.method==="POST")return handleMiniAppAction(request,env,kickCoordinator);if(url.pathname==="/interactions"&&request.method==="POST")return handleDiscord(request,env);if(url.pathname==="/telegram/webhook"&&request.method==="POST")return handleTelegram(request,env);if(url.pathname==="/admin/register"&&request.method==="POST")return handleRegister(request,env);if(url.pathname==="/admin/telegram/register"&&request.method==="POST")return handleTelegramRegister(request,env);return new Response("Veil Arena is online.",{headers:{"content-type":"text/plain; charset=utf-8"}});}};