import { InteractionType,InteractionResponseType,verifyDiscordRequest,jsonResponse,interactionMessage,interactionUpdate,button,actionRow,userFromInteraction,registerGuildCommands,createChannelMessage,createChannelTextFile } from "./discord.js";
import { createGame,addPlayer,removePlayer,startGame,castCrowdVote } from "./core/engine.js";
import { ensureSchema,saveGame,loadGame,loadActiveGameForChannel,loadFinishedGameForGuild,getGuildConfig,setGuildTheme,loadPlayerStats,loadArenaLeaderboard } from "./storage.js";
import { getTheme } from "./themes/index.js";
import { rulesForTheme } from "./rules.js";
import { FULL_TILT_GUILD_ID,VIBE_QUEEN_GUILD_ID,themeForGuild } from "./server-config.js";
import { buildArenaLog } from "./logs.js";
export { ArenaCoordinator } from "./coordinator.js";

function playerList(game){const players=Object.values(game.players);if(!players.length)return"Nobody has entered yet.";return players.map((p,i)=>`${i+1}. **${p.displayName}**`).join("\n");}
function registrationMessage(game){const theme=getTheme(game.themeId);return`# ${theme.labels.arena}\nRegistration is open.\n🎭 **SERVER THEME: ${theme.displayName}**\n\n${playerList(game)}\n\n**${Object.keys(game.players).length} entered**`;}
function registrationComponents(game){return[actionRow(button(`arena:join:${game.id}`,"ENTER ARENA",3,false,"⚔️"),button(`arena:leave:${game.id}`,"LEAVE",2),button(`arena:start:${game.id}`,"START",1,false,"▶️"))];}
function voteSelect(game,page=0){const per=25,total=Math.max(1,Math.ceil(game.aliveIds.length/per)),safe=Math.max(0,Math.min(page,total-1)),ids=game.aliveIds.slice(safe*per,(safe+1)*per);const select={type:3,custom_id:`arena:vote_cast:${game.id}:${safe}`,placeholder:"Choose a player...",min_values:1,max_values:1,options:ids.map(id=>({label:game.players[id]?.displayName?.slice(0,100)||"Unknown",value:id}))};const rows=[{type:1,components:[select]}];if(total>1)rows.push(actionRow(button(`arena:vote_open:${game.id}:${safe-1}`,"PREV",2,safe===0),button(`arena:vote_open:${game.id}:${safe+1}`,"NEXT",2,safe>=total-1)));return{rows,page:safe,totalPages:total};}
async function kickCoordinator(env,channelId,action="kick"){if(!env.ARENA_COORDINATOR)return;const id=env.ARENA_COORDINATOR.idFromName(channelId),stub=env.ARENA_COORDINATOR.get(id);await stub.fetch("https://arena.internal/",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({action,channelId})});}
async function scheduleMessageDelete(env,channelId,messageId,delayMs=30000){if(!env.ARENA_COORDINATOR||!messageId)return;const id=env.ARENA_COORDINATOR.idFromName(`delete:${messageId}`),stub=env.ARENA_COORDINATOR.get(id);await stub.fetch("https://arena.internal/",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({action:"delete_message",channelId,messageId,delayMs})});}
async function themeIdForGuild(env,guildId){const config=await getGuildConfig(env.DB,guildId),themeId=themeForGuild(guildId,config.theme_id);if(themeId!==config.theme_id)await setGuildTheme(env.DB,guildId,themeId);return themeId;}

async function handleArenaCommand(interaction,env){
  if(!interaction.guild_id)return interactionMessage("Arena can only run inside a server.",[],true);
  if(!env.DB)return interactionMessage("Arena database is not configured yet.",[],true);
  await ensureSchema(env.DB);
  const option=interaction.data?.options?.[0],sub=option?.name||"start",channelId=interaction.channel_id,guildId=interaction.guild_id,user=userFromInteraction(interaction);
  if(sub==="rules"){const themeId=await themeIdForGuild(env,guildId);const posted=await createChannelMessage(channelId,env.DISCORD_BOT_TOKEN,{content:rulesForTheme(themeId)});await scheduleMessageDelete(env,channelId,posted?.id,30000);return interactionMessage("📜 Arena rules posted for **30 seconds**.",[],true);}
  let game=await loadActiveGameForChannel(env.DB,channelId);
  if(sub==="start"){if(game)return interactionMessage("There is already an Arena game active in this channel.",[],true);const themeId=await themeIdForGuild(env,guildId);game=createGame({guildId,channelId,hostId:user.id,themeId});addPlayer(game,user);await saveGame(env.DB,game);return interactionMessage(registrationMessage(game),registrationComponents(game));}
  return interactionMessage("Unknown Arena command.",[],true);
}
function statsText(user,stats){const games=stats?.games_played||0,wins=stats?.wins||0,kills=stats?.total_kills||0,revives=stats?.total_revivals||0,best=stats?.max_kills_single_game||0,crowd=stats?.crowd_survivals||0,rate=games?((wins/games)*100).toFixed(1):"0.0";return`# ⚔️ ${user.displayName}'S ARENA STATS\n\n**Arenas Played:** ${games}\n**Wins:** ${wins}\n**Total Kills:** ${kills}\n**Total Revivals:** ${revives}\n**Most Kills in One Arena:** ${best}\n**Crowd Votes Survived:** ${crowd}\n**Win Rate:** ${rate}%\n\n*Stats track from Arena's official launch in this server.*`;}
async function handleStatsCommand(interaction,env){if(!interaction.guild_id)return interactionMessage("Arena stats only exist inside a server.",[],true);if(!env.DB)return interactionMessage("Arena database is not configured yet.",[],true);await ensureSchema(env.DB);const user=userFromInteraction(interaction),stats=await loadPlayerStats(env.DB,interaction.guild_id,user.id);return interactionMessage(statsText(user,stats));}
function boardSection(title,rows){if(!rows?.length)return`**${title}**\nNo records yet.`;return`**${title}**\n${rows.map((r,i)=>`${i+1}. ${r.display_name} — **${r.value}**`).join("\n")}`;}
async function handleLeaderboardCommand(interaction,env){if(!interaction.guild_id)return interactionMessage("Arena leaderboards only exist inside a server.",[],true);if(!env.DB)return interactionMessage("Arena database is not configured yet.",[],true);await ensureSchema(env.DB);const b=await loadArenaLeaderboard(env.DB,interaction.guild_id,5);const content=["# 🏆 ARENA LEADERBOARD",boardSection("⚔️ MOST ARENAS PLAYED",b.gamesPlayed),boardSection("👑 MOST WINS",b.wins),boardSection("💀 TOTAL KILLS",b.kills),boardSection("🕯️ TOTAL REVIVALS",b.revivals),boardSection("🔥 MOST KILLS IN ONE ARENA",b.singleGameKills),boardSection("👁️ CROWD VOTES SURVIVED",b.crowdSurvivals)].join("\n\n");return interactionMessage(content);}
async function handleLogCommand(interaction,env){if(!interaction.guild_id)return interactionMessage("Arena logs only exist inside a server.",[],true);if(!env.DB)return interactionMessage("Arena database is not configured yet.",[],true);await ensureSchema(env.DB);const requested=Math.max(1,Number(interaction.data?.options?.find(x=>x.name==="match")?.value||1));const game=await loadFinishedGameForGuild(env.DB,interaction.guild_id,requested-1);if(!game)return interactionMessage(`I couldn't find completed Arena match #${requested} for this server.`,[],true);const log=buildArenaLog(game,requested),filename=`arena-match-${requested}-${game.id.slice(0,8)}.txt`;await createChannelTextFile(interaction.channel_id,env.DISCORD_BOT_TOKEN,filename,log,`📜 **Arena Match ${requested} narration log**`);return interactionMessage(`Done — I posted **Arena Match ${requested}** as a text file in this channel.\n\nUse \`/arenalog match:2\` for the previous match, \`match:3\` for the one before that, etc.`,[],true);}
async function handleComponent(interaction,env){const parts=(interaction.data?.custom_id||"").split(":"),action=parts[1],gameId=parts[2],user=userFromInteraction(interaction);if(!gameId||!user||!env.DB)return interactionMessage("Arena couldn't read that action.",[],true);await ensureSchema(env.DB);const game=await loadGame(env.DB,gameId);if(!game)return interactionMessage("That Arena game no longer exists.",[],true);if(action==="join"){try{addPlayer(game,user);await saveGame(env.DB,game);return interactionUpdate(registrationMessage(game),registrationComponents(game));}catch(e){return interactionMessage(e.message,[],true);}}if(action==="leave"){try{removePlayer(game,user.id);await saveGame(env.DB,game);return interactionUpdate(registrationMessage(game),registrationComponents(game));}catch(e){return interactionMessage(e.message,[],true);}}if(action==="start"){if(user.id!==game.hostId)return interactionMessage("Only the Arena host can start the game.",[],true);try{startGame(game);await saveGame(env.DB,game);await kickCoordinator(env,game.channelId,"kick");const theme=getTheme(game.themeId);return interactionUpdate(`# ${theme.labels.arena}\nThe doors close. **${game.aliveIds.length} players** are inside.\n\nThe first round begins now.`,[]);}catch(e){return interactionMessage(e.message,[],true);}}if(action==="vote_open"){if(!game.crowdVote||game.crowdVote.status!=="open")return interactionMessage("The audience vote is closed.",[],true);if(game.aliveIds.includes(user.id))return interactionMessage("You're still fighting. The audience gets this vote.",[],true);const {rows,page,totalPages}=voteSelect(game,Number(parts[3]||0)),voteName=game.themeId==="full_tilt"?"Final Bet":"Final Scare";return interactionMessage(`**Choose who enters the ${voteName}.**\nPage ${page+1}/${totalPages}\nYou may change your vote until voting closes.`,rows,true);}if(action==="vote_cast"){if(!game.crowdVote||game.crowdVote.status!=="open")return interactionMessage("The audience vote is closed.",[],true);if(game.aliveIds.includes(user.id))return interactionMessage("You're still fighting. The audience gets this vote.",[],true);const id=interaction.data?.values?.[0];try{castCrowdVote(game,user.id,id);await saveGame(env.DB,game);return interactionMessage(`Vote locked on **${game.players[id]?.displayName||"Unknown"}**. You can change it before time runs out.`,[],true);}catch(e){return interactionMessage(e.message,[],true);}}return interactionMessage("Unknown Arena action.",[],true);}
async function handleDiscord(request,env){const raw=await request.text();if(!await verifyDiscordRequest(request,env.DISCORD_PUBLIC_KEY,raw))return new Response("Bad signature",{status:401});const i=JSON.parse(raw);if(i.type===InteractionType.PING)return jsonResponse({type:InteractionResponseType.PONG});if(i.type===InteractionType.APPLICATION_COMMAND){if(i.data?.name==="arena")return handleArenaCommand(i,env);if(i.data?.name==="arenastats")return handleStatsCommand(i,env);if(i.data?.name==="arenaleaderboard")return handleLeaderboardCommand(i,env);if(i.data?.name==="arenalog")return handleLogCommand(i,env);}if(i.type===InteractionType.MESSAGE_COMPONENT&&i.data?.custom_id?.startsWith("arena:"))return handleComponent(i,env);return interactionMessage("Veil doesn't know that Arena action yet.",[],true);}
async function handleRegister(request,env){const provided=request.headers.get("x-admin-secret");if(!env.ADMIN_SECRET||provided!==env.ADMIN_SECRET)return new Response("Unauthorized",{status:401});if(!env.DISCORD_APPLICATION_ID||!env.DISCORD_BOT_TOKEN)return jsonResponse({ok:false,error:"Discord credentials missing"},500);if(!env.DB)return jsonResponse({ok:false,error:"Arena database missing"},500);await ensureSchema(env.DB);const body=await request.json().catch(()=>({}));if(!body.guildId)return jsonResponse({ok:false,error:"guildId required"},400);const themeId=themeForGuild(body.guildId,body.themeId||"vibe_queen_slots");const commands=await registerGuildCommands(env.DISCORD_APPLICATION_ID,body.guildId,env.DISCORD_BOT_TOKEN);await setGuildTheme(env.DB,body.guildId,themeId);return jsonResponse({ok:true,themeId,commands});}
function setupPage({title,guildId,themeId,doneText}){return`<!doctype html><html><head><meta name="viewport" content="width=device-width,initial-scale=1"><title>${title} Arena Setup</title><style>body{font-family:system-ui;margin:0;background:#111;color:#fff;display:grid;place-items:center;min-height:100vh}.card{width:min(92vw,460px);background:#1c1c1c;padding:24px;border-radius:18px}input,button{width:100%;box-sizing:border-box;padding:14px;border-radius:10px;font-size:16px}input{margin:12px 0;background:#0d0d0d;color:#fff;border:1px solid #444}button{border:0;font-weight:700}#out{white-space:pre-wrap;margin-top:14px;color:#ddd}</style></head><body><div class="card"><h1>${title} Arena</h1><p>Enter the Cloudflare ADMIN_SECRET you already know. It is sent directly to your Arena Worker and is not stored by this page.</p><input id="secret" type="password" placeholder="ADMIN_SECRET"><button id="go">REGISTER ARENA</button><div id="out"></div></div><script>go.onclick=async()=>{out.textContent='Registering…';try{const r=await fetch('/admin/register',{method:'POST',headers:{'content-type':'application/json','x-admin-secret':secret.value},body:JSON.stringify({guildId:'${guildId}',themeId:'${themeId}'})});const text=await r.text();out.textContent=r.ok?'✅ ${doneText}':'❌ '+r.status+' '+text}catch(e){out.textContent='❌ '+e.message}}</script></body></html>`;}
export default{async fetch(request,env){const url=new URL(request.url);if(url.pathname==="/health")return jsonResponse({ok:true,service:"veil-arena",status:"ready",database:Boolean(env.DB),coordinator:Boolean(env.ARENA_COORDINATOR),discordConfigured:Boolean(env.DISCORD_PUBLIC_KEY&&env.DISCORD_BOT_TOKEN&&env.DISCORD_APPLICATION_ID)});if(url.pathname==="/setup/full-tilt"&&request.method==="GET")return new Response(setupPage({title:"Full Tilt",guildId:FULL_TILT_GUILD_ID,themeId:"full_tilt",doneText:"Done. Go back to Full Tilt and type /arena."}),{headers:{"content-type":"text/html; charset=utf-8","cache-control":"no-store"}});if(url.pathname==="/setup/vibe-queen"&&request.method==="GET")return new Response(setupPage({title:"Vibe Queen Slots: After Dark",guildId:VIBE_QUEEN_GUILD_ID,themeId:"vibe_queen_slots",doneText:"Done. Go back to Vibe Queen Slots and type /arena."}),{headers:{"content-type":"text/html; charset=utf-8","cache-control":"no-store"}});if(url.pathname==="/interactions"&&request.method==="POST")return handleDiscord(request,env);if(url.pathname==="/admin/register"&&request.method==="POST")return handleRegister(request,env);return new Response("Veil Arena is online.",{headers:{"content-type":"text/plain; charset=utf-8"}});}};
